import type { TranslationDictionary } from "../types";

export const en: TranslationDictionary = {
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    back: "Back",
    close: "Close",
    search: "Search",
    loading: "Loading...",
    processing: "Processing...",
    confirm: "Confirm",
    error: "Something went wrong",
    success: "Success",
    copied: "Link copied!",
    copyLink: "Copy Link",
    share: "Share",
    notFound: "Not found",
    empty: "No data available",
    filter: "Filter",
    all: "All",
    status: "Status",
    actions: "Actions",
    retry: "Try Again",
  },
  nav: {
    home: "Home",
    explore: "Explore",
    dashboard: "Dashboard",
    wallet: "Wallet",
    chat: "Messages",
    notifications: "Notifications",
    profile: "Profile",
    pricing: "Pricing",
    howItWorks: "How It Works",
    login: "Sign In",
    register: "Sign Up",
    logout: "Sign Out",
    adminPanel: "Admin Panel",
    feed: "Feed",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    selectLanguage: "Language",
    closeMenu: "Close menu",
    openMenu: "Open menu",
  },
  hero: {
    badge: "⚡ One Link for All Your Creator Earnings",
    titlePart1: "Accept Donations, Sell Digital Files &",
    titleAccent: "Build Community",
    titlePart2: "in One Link",
    subtitle: "Replace 3 fragmented platforms with one elegant personal hub. Accept instant payments from fans via QRIS, e-wallets, and Bank Transfers with zero monthly fees.",
    ctaPrimary: "Claim Your yourpage.id Link — Free",
    ctaSecondary: "Explore Creators",
    trustFree: "100% Free Forever",
    trustSetup: "2-Minute Setup",
    trustPayment: "Supports QRIS & All Major Banks",
    statCredit: "1 Credit",
    statCreditLabel: "= IDR 1,000",
    statFee: "5%",
    statFeeLabel: "Lowest Platform Fee",
    statSetup: "2 Minutes",
    statSetupLabel: "Ready for Bio",
    statPayout: "24 Hours",
    statPayoutLabel: "Direct Bank Payout",
  },
  earningsCard: {
    title: "Creator Dashboard",
    monthlyEarnings: "Earnings this month",
    growthLabel: "+18% from last month",
    newDonation: "New donation",
    productSold: "Product sold",
    illustrationNote: "*Dashboard preview illustration",
  },
  howItWorks: {
    eyebrow: "Super Simple",
    title: "Get Started in 3 Steps",
    step1Title: "Claim Your Custom Handle",
    step1Desc: "Sign up free and secure your personal yourpage.id/c/yourname link in 2 minutes.",
    step2Title: "Upload Files & Set Prices",
    step2Desc: "Set prices for digital assets, create donation goals, or lock exclusive posts.",
    step3Title: "Earn & Cash Out to Bank",
    step3Desc: "Fans pay via QRIS and local e-wallets. Credits go straight to your wallet, ready to cash out.",
  },
  howItWorksPage: {
    heroTitle: "How YourPage Works",
    heroSubtitle: "The complete guide for creators and supporters",
    forCreatorsHeading: "🎨 For Creators",
    creatorStep1Title: "Free Registration",
    creatorStep1Desc: "Sign up with your email and claim your handle. It becomes your personal page link: yourpage.id/c/username",
    creatorStep2Title: "Customize Profile",
    creatorStep2Desc: "Upload your avatar, banner, bio, and social links. Pro & Business plans can customize page theme colors.",
    creatorStep3Title: "Create Content & Products",
    creatorStep3Desc: "Publish free or paywalled posts (priced in Credits). Upload digital files such as e-books, presets, or templates.",
    creatorStep4Title: "Set Goals & Direct Chat",
    creatorStep4Desc: "Add interactive donation progress goals. Set pay-per-message rates for private DMs. Setup OBS live stream overlays.",
    creatorStep5Title: "Receive Payments",
    creatorStep5Desc: "Fans purchase items, send tips, and pay for chat. All earnings are credited straight to your digital wallet.",
    creatorStep6Title: "Direct Bank Payouts",
    creatorStep6Desc: "Verify your identity (KYC), then withdraw Credits to your local bank account. Minimum 100 Credits = Rp 100,000.",
    forSupportersHeading: "☕ For Supporters",
    supporterStep1Title: "Sign Up & Top-up",
    supporterStep1Desc: "Create a supporter account. Top-up Credits easily via QRIS and local payment channels (1 Credit = Rp 1,000).",
    supporterStep2Title: "Discover Creators",
    supporterStep2Desc: "Find your favorite creators on Explore. Follow them to catch the latest updates and exclusive drops in your Feed.",
    supporterStep3Title: "Support & Unlock",
    supporterStep3Desc: "Unlock premium articles, tip creators with personal messages, or start direct 1-on-1 conversations.",
    supporterStep4Title: "Lifetime Access",
    supporterStep4Desc: "All purchased digital downloads and locked posts remain permanently accessible in your personal Library.",
    feeHeading: "💰 Fee Structure",
    thTier: "Tier",
    thPrice: "Price",
    thFee: "Fee",
    thCreatorKeeps: "Creator Keeps",
    freePrice: "Free",
    proPrice: "Rp 49,000/mo",
    businessPrice: "Rp 149,000/mo",
    faqHeading: "❓ FAQ",
    faq1Q: "Is it completely free to start?",
    faq1A: "Yes! Creating an account is 100% free with no monthly subscription fees. Platform fees only apply when you make a sale.",
    faq2Q: "How fast are creator payouts processed?",
    faq2A: "Payout requests are processed and transferred within 24 business hours directly to your designated bank account.",
    faq3Q: "Can my purchased digital downloads disappear?",
    faq3A: "Never. All digital files and unlocked posts you purchase are saved permanently inside your personal Library.",
    faq4Q: "How does the Credit system work?",
    faq4A: "1 Credit equals exactly IDR 1,000. Top up via QRIS, spend on creator content, and cash out to bank accounts anytime.",
    ctaButton: "Get Started Now — Free",
  },
  features: {
    eyebrow: "All-in-One Platform",
    title: "Every Way to Monetize in a Single Link",
    subtitle: "You create great work. It's time to get paid for it.",
    paidPostsTitle: "Paid Posts",
    paidPostsDesc: "Lock premium posts. Fans unlock articles, comics, or video tutorials with a single tap.",
    digitalProductsTitle: "Digital Products",
    digitalProductsDesc: "Sell e-books, presets, templates, and courses with automated 24/7 instant delivery.",
    donationsTitle: "Donations & Goals",
    donationsDesc: "Receive tips and fan appreciation with transparent visual progress bar milestones.",
    paidChatTitle: "Paid 1-on-1 Chat",
    paidChatDesc: "Monetize consultation requests and personalized private messages at your own rate.",
    obsOverlayTitle: "OBS Stream Overlay",
    obsOverlayDesc: "Display real-time animated alerts, sound triggers, and fan GIFs during live streams.",
    secureContentTitle: "Protected Content",
    secureContentDesc: "Keep your files safe with expirable download links, dynamic watermarks, and anti-screenshot shields.",
    analyticsTitle: "Full Analytics",
    analyticsDesc: "Track your top-selling products, most loyal supporters, and monthly income trends.",
    customPageTitle: "Custom Branding",
    customPageDesc: "Customize accent colors, banner graphics, and social links to match your brand.",
  },
  feeTransparency: {
    eyebrow: "100% Transparent",
    title: "Low Fees. The Rest is Yours.",
    subtitle: "No hidden charges or surprise deductions. You always know exactly how much you take home from every sale.",
    youKeep: "You Keep",
    platformFee: "Platform Fee",
  },
  creditSystem: {
    eyebrow: "Single Currency",
    title: "Frictionless Credit System",
    subtitle: "One simple currency for all transactions across YourPage.",
    topupTitle: "Top-up",
    topupDesc1: "Pay Rp 50,000",
    topupDesc2: "→ Receive 50 Credits",
    buyContentTitle: "Buy Content",
    buyContentDesc1: "Post: 5 Credits",
    buyContentDesc2: "→ Deducted from wallet",
    donateTitle: "Donate",
    donateDesc1: "Send 10 Credits",
    donateDesc2: "→ Creator gets 8–9.5 C",
    withdrawTitle: "Withdraw",
    withdrawDesc1: "Withdraw 100 Credits",
    withdrawDesc2: "→ Rp 100,000 to bank",
  },
  pricing: {
    eyebrow: "Flexible Plans",
    title: "Choose the Right Plan",
    subtitle: "Start free today, upgrade whenever you scale. No locked-in monthly contracts.",
    popularBadge: "Most Popular",
    freeName: "Free",
    freePrice: "Free",
    freeSub: "forever",
    freeCta: "Start Selling Free",
    proName: "Pro",
    proPrice: "Rp 49,000",
    proSub: "/month (49 Credits)",
    proCta: "Get Pro",
    businessName: "Business",
    businessPrice: "Rp 149,000",
    businessSub: "/month (149 Credits)",
    businessCta: "Get Business",
    compareLink: "View full feature comparison table",
  },
  useCases: {
    eyebrow: "Who It's For",
    title: "Built for Every Creator",
    designerTitle: "Designers & Artists",
    designerDesc: "Sell Lightroom presets, UI kits, and wallpapers. Files deliver automatically upon purchase.",
    educatorTitle: "Educators & Writers",
    educatorDesc: "Share exclusive newsletters, guides, and masterclasses while building a dedicated community.",
    streamerTitle: "Streamers & Gamers",
    streamerDesc: "Receive real-time live tips, custom OBS overlays, and connect with supporters.",
  },
  finalCta: {
    title: "Ready to Monetize Your Content?",
    subtitle: "Free forever. Upgrade anytime. Withdraw anytime.",
    button: "Get Started Now — Free",
  },
  footer: {
    description: "The all-in-one monetization hub for digital creators in Indonesia.",
    productHeading: "Product",
    pricingLink: "Pricing",
    howItWorksLink: "How It Works",
    exploreLink: "Explore Creators",
    legalHeading: "Legal",
    termsLink: "Terms of Service",
    privacyLink: "Privacy Policy",
    contactLink: "Contact",
    socialHeading: "Follow Us",
    copyright: "© 2026 YourPage. All rights reserved.",
  },
  auth: {
    loginTitle: "Welcome Back 👋",
    loginSubtitle: "Sign in to your account",
    registerTitle: "Create New Account ✨",
    registerSubtitle: "Free registration in 2 minutes",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    usernameLabel: "Username",
    roleSelectorLabel: "I want to register as",
    roleSupporterLabel: "Supporter",
    roleSupporterDesc: "Buy content, send tips, message favorite creators",
    roleCreatorLabel: "Creator",
    roleCreatorDesc: "Sell digital content, accept tips, open custom storefront",
    referralLabel: "Referral Code (optional)",
    forgotPasswordLink: "Forgot password?",
    loginButton: "Sign In",
    registerButton: "Create Account",
    orDivider: "or",
    loginWithQR: "Sign In with QR Code",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account yet?",
    termsAgreement: "By signing up, you agree to our Terms of Service and Privacy Policy.",
  },
  creatorPage: {
    notFound: "Creator not found",
    followersCount: "Followers",
    postsCount: "Posts",
    editProfile: "Edit Profile",
    shareProfile: "Share",
    followButton: "Follow",
    unfollowButton: "Unfollow",
    donateButton: "Donate",
    chatButton: "Chat",
    topSupporterTitle: "Top Supporters",
    becomeMemberTitle: "Join Membership",
    memberBadge: "✓ Member",
    perMonth: "Credits/month",
    supportCreator: "Support",
    donateModalTitle: "Send Appreciation to",
    donateSuccessTitle: "Donation Sent! 🎉",
    donateSuccessDesc: "Thank you for supporting and appreciating local creators.",
    donateAgain: "Donate Again",
    customAmountPlaceholder: "Custom amount (min {min})",
    messagePlaceholder: "Message (optional)",
    sendDonationButton: "Send",
    paidByCredits: "Paid with Credits from your wallet",
    tabPosts: "Posts",
    tabProducts: "Catalog",
    tabMembership: "Memberships",
    emptyPostsTitle: "No posts yet",
    emptyPostsDesc: "This creator is preparing their next release. Follow to be notified when it's live!",
    emptyProductsTitle: "No products yet",
    emptyProductsDesc: "No digital products available right now. Feel free to message the creator for requests.",
  },
  post: {
    lockedTitle: "Exclusive Locked Content",
    lockedDesc: "Buy once, access forever in your Library.",
    unlockButton: "Unlock Exclusive Post",
    previewBadge: "Preview",
    commentsTitle: "Comments",
    emptyComments: "No comments yet. Be the first to leave a message!",
    writeComment: "Write a comment...",
    sendComment: "Post",
  },
  product: {
    filesIncluded: "Included Files",
    salesCount: "sold",
    buyButton: "Buy Now",
    downloadButton: "Download File",
    purchasedBadge: "Purchased",
    topupRequired: "Insufficient credits. Please top-up.",
  },
  wallet: {
    creditBalance: "Credit Balance",
    topupButton: "Top-up Credits",
    withdrawButton: "Withdraw Funds",
    creditRateNote: "1 Credit = Rp 1,000",
    transactionHistory: "Transaction History",
    emptyTransactions: "No transactions yet",
  },
  dashboard: {
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    totalEarnings: "Total Earnings",
    setupTitle: "Page Setup",
    newPostButton: "New Post",
    myPageButton: "My Storefront",
  },
  chat: {
    title: "Chat",
    newChatTitle: "New Chat",
    newChatSubtitle: "Send your first message",
    pricePerMessage: "Each message costs {price} Credits",
    inputPlaceholder: "Write a message...",
    sendButton: "Send",
    sendFailed: "Failed to send message",
    conversationsCount: "{count} conversations",
    emptyConversationsTitle: "No conversations yet",
    emptyConversationsDesc: "Visit a creator's page to start chatting",
    selectConversationTitle: "Select a conversation",
    selectConversationDesc: "Choose a chat from the list on the left",
    startConversationPrompt: "Start a conversation...",
    paidBadge: "Paid",
    sendMessageAria: "Send message",
    loadFailed: "Failed to load chat",
  },
};
