import type { TranslationDictionary } from "../types";

export const en: TranslationDictionary = {
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    back: "Back",
    close: "Close",
    search: "Search",
    loading: "Loading...",
    processing: "Processing...",
    confirm: "Confirm",
    error: "Something went wrong",
    success: "Success",
    copied: "Link copied!",
    copyLink: "Copy Link",
    share: "Share",
    notFound: "Not found",
    empty: "No data available",
    filter: "Filter",
    all: "All",
    status: "Status",
    actions: "Actions",
    retry: "Try Again",
    notFoundTitle: "Page Not Found",
    notFoundDesc: "The page you're looking for doesn't exist or has been moved.",
    backToHome: "Back to Home",
    errorTitle: "Something Went Wrong",
    errorDesc: "Try refreshing the page.",
    refresh: "Refresh",
  },
  nav: {
    home: "Home",
    explore: "Explore",
    dashboard: "Dashboard",
    wallet: "Wallet",
    chat: "Messages",
    notifications: "Notifications",
    profile: "Profile",
    pricing: "Pricing",
    howItWorks: "How It Works",
    login: "Sign In",
    register: "Sign Up",
    logout: "Sign Out",
    adminPanel: "Admin Panel",
    feed: "Feed",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    selectLanguage: "Language",
    closeMenu: "Close menu",
    openMenu: "Open menu",
  },
  hero: {
    badge: "⚡ One Link for All Your Creator Earnings",
    titlePart1: "Accept Donations, Sell Digital Files &",
    titleAccent: "Build Community",
    titlePart2: "in One Link",
    subtitle: "Replace 3 fragmented platforms with one elegant personal hub. Accept instant payments from fans via QRIS, e-wallets, and Bank Transfers with zero monthly fees.",
    ctaPrimary: "Claim Your yourpage.id Link — Free",
    ctaSecondary: "Explore Creators",
    trustFree: "100% Free Forever",
    trustSetup: "2-Minute Setup",
    trustPayment: "Supports QRIS & All Major Banks",
    statCredit: "1 Credit",
    statCreditLabel: "= IDR 1,000",
    statFee: "5%",
    statFeeLabel: "Lowest Platform Fee",
    statSetup: "2 Minutes",
    statSetupLabel: "Ready for Bio",
    statPayout: "24 Hours",
    statPayoutLabel: "Direct Bank Payout",
  },
  earningsCard: {
    title: "Creator Dashboard",
    monthlyEarnings: "Earnings this month",
    growthLabel: "+18% from last month",
    newDonation: "New donation",
    productSold: "Product sold",
    illustrationNote: "*Dashboard preview illustration",
  },
  compLanding: {
    dashboardTitle: "Creator Dashboard",
    monthlyEarnings: "Earnings this month",
    growthLabel: "+18% from last month",
    chartAriaLabel: "Revenue trend chart showing steady growth",
    illustrationNote: "*Dashboard preview illustration",
    newDonation: "New donation",
    productSold: "Product sold",
    ebookDesign: "E-book Design",
    takesFromEach: "you receive from each transaction",
    youKeepPercent: "You {percent}%",
    platformFeePercent: "Platform fee {percent}%",
    exampleDonation: "Example: {amount} donation received \u2192 you get {takeHome}",
  },
  howItWorks: {
    eyebrow: "Super Simple",
    title: "Get Started in 3 Steps",
    step1Title: "Claim Your Custom Handle",
    step1Desc: "Sign up free and secure your personal yourpage.id/c/yourname link in 2 minutes.",
    step2Title: "Upload Files & Set Prices",
    step2Desc: "Set prices for digital assets, create donation goals, or lock exclusive posts.",
    step3Title: "Earn & Cash Out to Bank",
    step3Desc: "Fans pay via QRIS and local e-wallets. Credits go straight to your wallet, ready to cash out.",
  },
  howItWorksPage: {
    heroTitle: "How YourPage Works",
    heroSubtitle: "The complete guide for creators and supporters",
    forCreatorsHeading: "🎨 For Creators",
    creatorStep1Title: "Free Registration",
    creatorStep1Desc: "Sign up with your email and claim your handle. It becomes your personal page link: yourpage.id/c/username",
    creatorStep2Title: "Customize Profile",
    creatorStep2Desc: "Upload your avatar, banner, bio, and social links. Pro & Business plans can customize page theme colors.",
    creatorStep3Title: "Create Content & Products",
    creatorStep3Desc: "Publish free or paywalled posts (priced in Credits). Upload digital files such as e-books, presets, or templates.",
    creatorStep4Title: "Set Goals & Direct Chat",
    creatorStep4Desc: "Add interactive donation progress goals. Set pay-per-message rates for private DMs. Setup OBS live stream overlays.",
    creatorStep5Title: "Receive Payments",
    creatorStep5Desc: "Fans purchase items, send tips, and pay for chat. All earnings are credited straight to your digital wallet.",
    creatorStep6Title: "Direct Bank Payouts",
    creatorStep6Desc: "Verify your identity (KYC), then withdraw Credits to your local bank account. Minimum 100 Credits = Rp 100,000.",
    forSupportersHeading: "☕ For Supporters",
    supporterStep1Title: "Sign Up & Top-up",
    supporterStep1Desc: "Create a supporter account. Top-up Credits easily via QRIS and local payment channels (1 Credit = Rp 1,000).",
    supporterStep2Title: "Discover Creators",
    supporterStep2Desc: "Find your favorite creators on Explore. Follow them to catch the latest updates and exclusive drops in your Feed.",
    supporterStep3Title: "Support & Unlock",
    supporterStep3Desc: "Unlock premium articles, tip creators with personal messages, or start direct 1-on-1 conversations.",
    supporterStep4Title: "Lifetime Access",
    supporterStep4Desc: "All purchased digital downloads and locked posts remain permanently accessible in your personal Library.",
    feeHeading: "💰 Fee Structure",
    thTier: "Tier",
    thPrice: "Price",
    thFee: "Fee",
    thCreatorKeeps: "Creator Keeps",
    freePrice: "Free",
    proPrice: "Rp 49,000/mo",
    businessPrice: "Rp 149,000/mo",
    faqHeading: "❓ FAQ",
    faq1Q: "Is it completely free to start?",
    faq1A: "Yes! Creating an account is 100% free with no monthly subscription fees. Platform fees only apply when you make a sale.",
    faq2Q: "How fast are creator payouts processed?",
    faq2A: "Payout requests are processed and transferred within 24 business hours directly to your designated bank account.",
    faq3Q: "Can my purchased digital downloads disappear?",
    faq3A: "Never. All digital files and unlocked posts you purchase are saved permanently inside your personal Library.",
    faq4Q: "How does the Credit system work?",
    faq4A: "1 Credit equals exactly IDR 1,000. Top up via QRIS, spend on creator content, and cash out to bank accounts anytime.",
    ctaButton: "Get Started Now — Free",
  },
  features: {
    eyebrow: "All-in-One Platform",
    title: "Every Way to Monetize in a Single Link",
    subtitle: "You create great work. It's time to get paid for it.",
    paidPostsTitle: "Paid Posts",
    paidPostsDesc: "Lock premium posts. Fans unlock articles, comics, or video tutorials with a single tap.",
    digitalProductsTitle: "Digital Products",
    digitalProductsDesc: "Sell e-books, presets, templates, and courses with automated 24/7 instant delivery.",
    donationsTitle: "Donations & Goals",
    donationsDesc: "Receive tips and fan appreciation with transparent visual progress bar milestones.",
    paidChatTitle: "Paid 1-on-1 Chat",
    paidChatDesc: "Monetize consultation requests and personalized private messages at your own rate.",
    obsOverlayTitle: "OBS Stream Overlay",
    obsOverlayDesc: "Display real-time animated alerts, sound triggers, and fan GIFs during live streams.",
    secureContentTitle: "Protected Content",
    secureContentDesc: "Keep your files safe with expirable download links, dynamic watermarks, and anti-screenshot shields.",
    analyticsTitle: "Full Analytics",
    analyticsDesc: "Track your top-selling products, most loyal supporters, and monthly income trends.",
    customPageTitle: "Custom Branding",
    customPageDesc: "Customize accent colors, banner graphics, and social links to match your brand.",
  },
  feeTransparency: {
    eyebrow: "100% Transparent",
    title: "Low Fees. The Rest is Yours.",
    subtitle: "No hidden charges or surprise deductions. You always know exactly how much you take home from every sale.",
    youKeep: "You Keep",
    platformFee: "Platform Fee",
  },
  creditSystem: {
    eyebrow: "Single Currency",
    title: "Frictionless Credit System",
    subtitle: "One simple currency for all transactions across YourPage.",
    topupTitle: "Top-up",
    topupDesc1: "Pay Rp 50,000",
    topupDesc2: "→ Receive 50 Credits",
    buyContentTitle: "Buy Content",
    buyContentDesc1: "Post: 5 Credits",
    buyContentDesc2: "→ Deducted from wallet",
    donateTitle: "Donate",
    donateDesc1: "Send 10 Credits",
    donateDesc2: "→ Creator gets 8–9.5 C",
    withdrawTitle: "Withdraw",
    withdrawDesc1: "Withdraw 100 Credits",
    withdrawDesc2: "→ Rp 100,000 to bank",
  },
  pricing: {
    eyebrow: "Flexible Plans",
    title: "Choose the Right Plan",
    subtitle: "Start free today, upgrade whenever you scale. No locked-in monthly contracts.",
    popularBadge: "Most Popular",
    freeName: "Free",
    freePrice: "Free",
    freeSub: "forever",
    freeCta: "Start Selling Free",
    proName: "Pro",
    proPrice: "Rp 49,000",
    proSub: "/month (49 Credits)",
    proCta: "Get Pro",
    businessName: "Business",
    businessPrice: "Rp 149,000",
    businessSub: "/month (149 Credits)",
    businessCta: "Get Business",
    compareLink: "View full feature comparison table",
  },
  useCases: {
    eyebrow: "Who It's For",
    title: "Built for Every Creator",
    designerTitle: "Designers & Artists",
    designerDesc: "Sell Lightroom presets, UI kits, and wallpapers. Files deliver automatically upon purchase.",
    educatorTitle: "Educators & Writers",
    educatorDesc: "Share exclusive newsletters, guides, and masterclasses while building a dedicated community.",
    streamerTitle: "Streamers & Gamers",
    streamerDesc: "Receive real-time live tips, custom OBS overlays, and connect with supporters.",
  },
  finalCta: {
    title: "Ready to Monetize Your Content?",
    subtitle: "Free forever. Upgrade anytime. Withdraw anytime.",
    button: "Get Started Now — Free",
  },
  footer: {
    description: "The all-in-one monetization hub for digital creators in Indonesia.",
    productHeading: "Product",
    pricingLink: "Pricing",
    howItWorksLink: "How It Works",
    exploreLink: "Explore Creators",
    legalHeading: "Legal",
    termsLink: "Terms of Service",
    privacyLink: "Privacy Policy",
    contactLink: "Contact",
    socialHeading: "Follow Us",
    copyright: "© 2026 YourPage. All rights reserved.",
  },
  auth: {
    loginTitle: "Welcome Back 👋",
    loginSubtitle: "Sign in to your account",
    registerTitle: "Create New Account ✨",
    registerSubtitle: "Free registration in 2 minutes",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    usernameLabel: "Username",
    usernamePlaceholder: "lowercase letters & numbers",
    roleSelectorLabel: "I want to register as",
    roleSupporterLabel: "Supporter",
    roleSupporterDesc: "Buy content, send tips, message favorite creators",
    roleCreatorLabel: "Creator",
    roleCreatorDesc: "Sell digital content, accept tips, open custom storefront",
    referralLabel: "Referral Code",
    referralOptional: "(optional)",
    referralPlaceholder: "Enter code",
    referralBonus: "🎁 You and your referrer each get 10 free Credits!",
    forgotPasswordLink: "Forgot password?",
    loginButton: "Sign In",
    registerButton: "Create Account",
    orDivider: "or",
    loginWithQR: "Sign In with QR Code",
    magicLinkButton: "Send Magic Link",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account yet?",
    termsAgreement: "By signing up, you agree to our Terms of Service and Privacy Policy.",
    invalidEmail: "Invalid email format",
    passwordMismatch: "Passwords do not match",
    passwordMin: "At least 8 characters",
    registerFailed: "Registration failed",
    hidePassword: "Hide password",
    showPassword: "Show password",
    sending: "Sending...",
    forgotTitle: "Forgot Password? 🔑",
    forgotSubtitle: "Enter your account email and we'll send a reset link.",
    forgotSendButton: "Send Reset Link",
    forgotSentTitle: "Email Sent!",
    forgotSentDesc: "Check {email} inbox and click the reset link. The link expires in 15 minutes.",
    forgotSendFailed: "Failed to send email",
    backToLogin: "← Back to Login",
    resetTitle: "Reset Password",
    resetSubtitle: "Create a new password for your account",
    resetNewPassword: "New Password",
    resetConfirmPassword: "Confirm Password",
    resetButton: "Reset Password",
    resetSuccessTitle: "Password reset successfully!",
    resetSuccessDesc: "Please log in with your new password.",
    resetFailed: "Failed to reset password",
    newPasswordPlaceholder: "At least 8 characters",
    invalidToken: "The link is invalid or has expired.",
    verifyTitle: "Verifying...",
    verifyDesc: "Verifying your email.",
    verifySuccess: "Email Verified! ✅",
    verifySuccessDesc: "Your account is now fully active.",
    verifyFailed: "Invalid Link",
    verifyFailedDesc: "The verification link has expired or is invalid.",
    verifying: "Verifying...",
    goToLogin: "Back to Login",
    openDashboard: "Open Dashboard",
    redirectingDashboard: "Redirecting to dashboard in {count} seconds...",
    qrConfirmTitle: "Approve login on another device?",
    qrConfirmDesc: "The device showing this code will be logged in as {name}. Continue only if you opened that login page yourself.",
    qrConfirming: "Approving…",
    qrConfirmSuccess: "Login approved",
    qrAddDesc: "The device showing the QR code is now logged in as {name}.",
    qrConfirmFailed: "The QR code is invalid or has expired.",
    qrMissingTitle: "Incomplete QR code",
    qrMissingDesc: "Re-scan the code from the login page on the device you want to sign in on.",
    qrLoginRequiredTitle: "Sign in on this device first",
    qrLoginRequiredDesc: "You need to be logged in on this phone before you can approve login on another device.",
    qrDoingDesc: "Creating confirmation...",
    qrCancelButton: "Cancel",
    qrConfirmButton: "Approve",
    loading: "Loading...",
    suspendedTitle: "Account Suspended",
    suspendedDesc: "Explain why your account should be restored:",
    appealDesc: "Explain why your account should be restored:",
    appealPlaceholder: "Write your appeal...",
    appealSendButton: "Submit Appeal",
    appealSubmitted: "Appeal submitted. We'll review it within 1-3 business days.",
    appealReviewing: "Reviewing...",
    appealSuccess: "Appeal sent",
    appealFailed: "Failed to send appeal",
    logoutButton: "Log out",
  },
  creatorPage: {
    notFound: "Creator not found",
    followersCount: "Followers",
    postsCount: "Posts",
    editProfile: "Edit Profile",
    shareProfile: "Share",
    followButton: "Follow",
    unfollowButton: "Unfollow",
    donateButton: "Donate",
    chatButton: "Chat",
    topSupporterTitle: "Top Supporters",
    becomeMemberTitle: "Join Membership",
    memberBadge: "✓ Member",
    perMonth: "Credits/month",
    supportCreator: "Support",
    donateModalTitle: "Send Appreciation to",
    donateSuccessTitle: "Donation Sent! 🎉",
    donateSuccessDesc: "Thank you for supporting and appreciating local creators.",
    donateAgain: "Donate Again",
    customAmountPlaceholder: "Custom amount (min {min})",
    messagePlaceholder: "Message (optional)",
    sendDonationButton: "Send",
    paidByCredits: "Paid with Credits from your wallet",
    tabPosts: "Posts",
    tabProducts: "Catalog",
    tabMembership: "Memberships",
    emptyPostsTitle: "No posts yet",
    emptyPostsDesc: "This creator is preparing their next release. Follow to be notified when it's live!",
    emptyProductsTitle: "No products yet",
    emptyProductsDesc: "No digital products available right now. Feel free to message the creator for requests.",
  },
  post: {
    lockedTitle: "Exclusive Locked Content",
    lockedDesc: "Buy once, access forever in your Library.",
    unlockButton: "Unlock Exclusive Post",
    previewBadge: "Preview",
    commentsTitle: "Comments",
    emptyComments: "No comments yet. Be the first to leave a message!",
    writeComment: "Write a comment...",
    sendComment: "Post",
    freeBadge: "Free",
    previewHint: "👆 Preview — buy to read more",
    paidContent: "Paid Content",
    buyForLogin: "Sign In to Buy",
    registerFree: "Don't have an account?",
    topupNow: "Top-up Credits Now",
    needCreditsPost: "You need {price} to unlock this content",
    processing: "Processing...",
    likeCount: "{count} Likes",
    commentCount: "{count} Comments",
    shareButton: "Share",
    shareAria: "Share post",
    copyLink: "Copy Link",
    linkCopied: "Link copied!",
    shareWhatsApp: "WhatsApp",
    shareTwitter: "Twitter",
    attachedDocument: "Attached document",
    insufficientCredits: "Insufficient credits.",
    openPost: "Open post",
    buyPost: "Buy — {price}",
  },
  product: {
    filesIncluded: "Included Files",
    salesCount: "sold",
    buyButton: "Buy Now",
    downloadButton: "Download File",
    purchasedBadge: "Purchased",
    topupRequired: "Insufficient credits. Please top-up.",
    inactiveBadge: "Inactive",
    deliveryLink: "Link",
    deliveryFile: "File",
    description: "Description",
    salesSold: "{count} sold",
    needCreditsProduct: "You need {price} to buy this product",
    alreadyPurchased: "Purchased",
    fileExpired: "expired",
    noFiles: "No files available yet.",
    creatorNoFiles: "Creator hasn't uploaded files for this product yet.",
    openLink: "Open Link",
    buyForLogin: "Sign In to Buy",
    registerFree: "Don't have an account?",
    topupNow: "Top-up Credits Now",
    processing: "Processing...",
    insufficientCredits: "Insufficient credits.",
    buyProduct: "Buy — {price}",
  },
  profilePage: {
    loading: "Loading...",
    dashboard: "Dashboard",
    upgradeToCreator: "Upgrade to Creator",
    redirecting: "Redirecting...",
  },
  wallet: {
    creditBalance: "Credit Balance",
    topupButton: "Top-up Credits",
    withdrawButton: "Withdraw Funds",
    creditRateNote: "1 Credit = Rp 1,000",
    transactionHistory: "Transaction History",
    emptyTransactions: "No transactions yet",
    withdrawToBank: "💰 Withdraw balance to your bank account",
    topupToStart: "Top up Credits to start transacting",
    topupSuccess: "Top-up Successful! 🎉",
    topupSuccessDesc: "{credits} Credits have been added to your balance.",
    paymentFailed: "Payment Failed",
    paymentSessionExpired: "Payment session expired. Please try again.",
    verifyingPayment: "Verifying payment...",
    verifyingPaymentDesc: "Just a moment, we're confirming with Stripe.",
    goToWallet: "Go to Wallet",
    paymentCancelled: "Payment Cancelled",
    noFundsCharged: "No funds were charged.",
    yourBalance: "Your balance: {balance} Credits",
    chooseAmount: "Choose Amount",
    noPaymentMethod: "⚠ No active payment method. Contact admin.",
    customAmountPlaceholder: "Custom amount (min 10,000)",
    youWillGet: "You will receive {credits} Credits",
    paymentMethod: "Payment Method",
    qris: "QRIS",
    qrisDesc: "GoPay · OVO · Dana · ShopeePay · Mobile Banking — verified within 24 hours",
    card: "Credit/Debit Card",
    stripeDesc: "Via Stripe — credits added automatically ⚡",
    payWithCard: "Pay with Card →",
    continueAction: "Continue →",
    transferAndUploadProof: "Transfer & Upload Proof",
    transferExactAmount: "Transfer exactly",
    uniqueCode: "Unique code:",
    uniqueCodeNote: "Amount must match exactly including the unique code so your transfer can be recognized automatically",
    scanQris: "Scan the QRIS below:",
    qrisChannels: "GoPay · OVO · Dana · ShopeePay · QRIS · Mobile Banking",
    qrisNotConfigured: "QRIS not configured by admin",
    senderName: "Sender Name",
    senderNamePlaceholder: "Name on account / e-wallet",
    transferProof: "Transfer Proof",
    maxFileSize: "Maximum 10MB",
    tapToUpload: "Tap to upload proof",
    sending: "Sending...",
    sendProof: "Send Transfer Proof",
    proofReceived: "Transfer Proof Received",
    pendingVerification: "Awaiting admin verification (within 24 hours). Credits will be added once approved.",
    notificationNote: "You will be notified once the admin verifies it.",
    topupAgain: "Top-up Again",
  },
  supporterHub: {
    feedTitle: "Feed",
    explore: "Explore",
    findCreators: "Find creators",
    donations: "Donations",
    history: "History",
    exploreCreators: "Explore Creators",
    emptyFeedTitle: "No content yet",
    emptyFeedDesc: "Follow creators to see their content.",
    purchasedPosts: "Purchased Posts",
    emptyPurchasedPosts: "No purchased posts yet",
    emptyPurchasedPostsDesc: "Buy content from your favorite creators",
    purchasedProducts: "Purchased Products",
    emptyPurchasedProducts: "No purchased products yet",
    emptyPurchasedProductsDesc: "Buy products from your favorite creators",
    donationsSent: "Donations Sent",
    totalDonations: "Total Donations",
    creatorsSupported: "Creators Supported",
    emptyDonationsSent: "You haven't sent any donations yet",
    supportCreatorsCta: "Support your favorite creators →",
    net: "Net:",
    totalSpent: "Total Spent",
    transactions: "Transactions",
    buyPost: "Buy Post",
    buyProduct: "Buy Product",
    donation: "Donation",
    topupCredit: "Top-up Credits",
    type: "Type",
    amount: "Amount",
    date: "Date",
    invoice: "Invoice",
    print: "Print",
    txId: "Transaction ID",
    creditAmount: "{credits} Credits",
    digitalReceipt: "Digital transaction receipt — YourPage",
    total: "Total:",
    income: "Incoming",
    outgoing: "Outgoing",
    settings: "Settings",
    profile: "Profile",
    blockedUsers: "Blocked Users",
    blockedUsersDesc: "Users you've blocked cannot follow, chat, or interact with you.",
    emptyBlocked: "You haven't blocked anyone yet.",
    blockedOn: "Blocked {date}",
    unblockButton: "Unblock",
    unblockSuccess: "User has been unblocked",
    unblockError: "Failed to unblock user",
    emptyDonations: "No donations yet.",
  },
  dashboard: {
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    totalEarnings: "Total Earnings",
    setupTitle: "Page Setup",
    newPostButton: "New Post",
    myPageButton: "My Storefront",
  },
  dashboardCore: {
    credit: "Credit",
    viewDetails: "View details",
    followers: "Followers",
    walletBalance: "Wallet",
    view: "View →",
    sales7Days: "7-Day Sales",
    total: "Total:",
    all: "All",
    noSalesData: "No sales data yet",
    createPost: "Create Post",
    createProduct: "Create Product",
    withdrawBalance: "Withdraw Balance",
    upgrade: "Upgrade",
    checkUploadAvatar: "Upload an avatar",
    checkWriteBio: "Write your bio",
    checkFirstPost: "Create your first post",
    checkVerifyKyc: "Verify KYC",
    analyticsAdvanced: "Advanced Analytics",
    analyticsProOnly: "Available for Pro and Business tiers.",
    upgradeNow: "Upgrade Now",
    analytics: "Analytics",
    exportCsv: "Export CSV",
    exportFailed: "Export failed.",
    loadFailed: "Failed to load data.",
    feeTier: "Fee Tier",
    upgradeLowerFee: "Upgrade for a lower fee →",
    statPosts: "Posts",
    statProducts: "Products",
    statFollowers: "Followers",
    statSales: "Sales",
    statRevenue: "Revenue",
    statDonations: "Donations",
    upgradeBusinessExport: "Upgrade to Business to export CSV",
    upgradeToBusiness: "Upgrade to Business",
    viewWallet: "View Wallet",
    profileSaved: "Profile saved successfully!",
    saveFailed: "Failed to save",
    viewPublicPage: "View Public Page",
    bannerAvatarTitle: "🖼️ Banner & Avatar",
    uploadBanner: "Upload banner (1500×400px)",
    changeBanner: "Change Banner",
    deleteBanner: "Delete banner",
    deleteBannerTitle: "Delete Banner?",
    deleteBannerDesc: "The banner will be deleted once you click Save.",
    changeAvatar: "Change Avatar",
    infoTitle: "📝 Information",
    bioLabel: "Bio",
    bioPlaceholder: "Example: Financial education content creator 💰 | Investing & budgeting tips for young Indonesians",
    charCount: "{count}/500 characters",
    categoryLabel: "Category",
    categoryHint: "Shown on the Explore page so supporters can easily find you",
    usernameHint: "Your username is used as your page link: urpage.online/c/{username}",
    socialTitle: "🔗 Social Media",
    channelUrlPlaceholder: "Channel URL",
    customizeTitle: "🎨 Customization",
    pageAccentColor: "Page accent color",
    saving: "Saving...",
    saveProfile: "Save Profile",
    donationsReceived: "Donations Received",
    totalDonations: "Total Donations",
    netReceived: "Net Received",
    donors: "Donors",
    anonymous: "Anonymous",
    net: "Net:",
    noDonations: "No donations yet",
    noDonationsDesc: "Share your page to start receiving donations",
  },
  chat: {
    title: "Chat",
    newChatTitle: "New Chat",
    newChatSubtitle: "Send your first message",
    pricePerMessage: "Each message costs {price} Credits",
    inputPlaceholder: "Write a message...",
    sendButton: "Send",
    sendFailed: "Failed to send message",
    conversationsCount: "{count} conversations",
    emptyConversationsTitle: "No conversations yet",
    emptyConversationsDesc: "Visit a creator's page to start chatting",
    selectConversationTitle: "Select a conversation",
    selectConversationDesc: "Choose a chat from the list on the left",
    startConversationPrompt: "Start a conversation...",
    paidBadge: "Paid",
    sendMessageAria: "Send message",
    loadFailed: "Failed to load chat",
  },
  feedPage: {
    title: "Feed",
    emptyTitle: "Feed is empty",
    emptyDesc: "Follow creators to see their posts here",
    findCreators: "Find Creators",
  },
  notifications: {
    title: "Notifications",
    markAllRead: "Mark all read",
    today: "Today",
    yesterday: "Yesterday",
    allReadTitle: "All caught up",
    allReadDesc: "New notifications will appear here",
  },
  upgrade: {
    title: "Become a Creator",
    subtitle: "Start monetizing your content on YourPage",
    displayNameLabel: "Display Name",
    displayNamePlaceholder: "Display name",
    pageSlugLabel: "Page Slug",
    slugPlaceholder: "username",
    pageHint: "Your page: yourpage.id/c/{slug}",
    upgradeFailed: "Upgrade failed",
    processing: "Processing...",
    upgradeButton: "Upgrade to Creator",
  },
  // --- Extended pricing keys (pricing page) ---
  pricingPage: {
    transparentPricing: "Transparent pricing",
    subtitle: "Start free, upgrade anytime. Higher tier, lower fees.",
    popular: "Popular",
    freePrice: "Free",
    perMonth: "per month",
    takeHome: "You keep {percent}% of each transaction",
    currentPlan: "Current Plan",
    upgrade: "Upgrade",
    startNow: "Get Started",
    featureComparison: "Feature Comparison",
    feature: "Feature",
    free: "Free",
    pro: "Pro",
    business: "Business",
    yes: "Yes",
    no: "No",
    postBerbayar: "Paid posts",
    produkDigital: "Digital products",
    storage: "Storage",
    platformFee: "Platform fee",
    kamuTerima: "You keep (take-home)",
    analytics: "Analytics",
    customPage: "Custom page",
    scheduledPosts: "Scheduled posts",
    prioritySupport: "Priority support",
    badgeKhusus: "Special badge",
  },
  explore: {
    searchPlaceholder: "Search creators...",
    clearSearch: "Clear search",
    all: "All",
    trending: "Trending",
    allCreators: "All Creators",
    verified: "Verified",
    notFound: "Not found",
    notFoundDesc: "Try different keywords for \u201c{query}\u201d",
    emptyTitle: "No creators yet",
    emptyDesc: "Creators will appear here",
    categories: {
      Gaming: "Gaming",
      Musik: "Music",
      Edukasi: "Education",
      Podcast: "Podcast",
      Seni: "Art",
      Teknologi: "Technology",
      Lifestyle: "Lifestyle",
      Lainnya: "Other",
    },
  },
  contact: {
    title: "Contact Us",
    subtitle: "Have a question or need help?",
    emailLabel: "Email",
    whatsappLabel: "WhatsApp",
  },
  legal: {
    termsTitle: "Terms of Service",
    privacyTitle: "Privacy Policy",
    lastUpdated: "Last updated: April 2026",
    terms: {
      section1Title: "1. About YourPage",
      section1Content: "YourPage is a content monetization platform for Indonesian creators. By using this service, you agree to the following terms and conditions.",
      section2Title: "2. Accounts",
      section2Item1: "You must be at least 17 years old to register.",
      section2Item2: "Information provided must be accurate and up to date.",
      section2Item3: "You are responsible for the security of your account.",
      section2Item4: "Each person may only have one account.",
      section3Title: "3. Content",
      section3Item1: "Creators are fully responsible for the content they publish.",
      section3Item2: "Publishing NSFW, violent, hateful, or illegal content is prohibited.",
      section3Item3: "YourPage reserves the right to remove content and suspend accounts that violate these terms.",
      section4Title: "4. Payments & Fees",
      section4Item1: "A 10% platform fee is applied to every transaction (posts, products, donations).",
      section4Item2: "Prices set by creators are inclusive of VAT.",
      section4Item3: "Purchased Credits cannot be converted back to cash.",
      section4Item4: "The minimum withdrawal amount is Rp 100,000.",
      section4Item5: "KYC (identity verification) is required for the first withdrawal.",
      section5Title: "5. Refunds & Disputes",
      section5Item1: "The platform does not provide automatic refunds.",
      section5Item2: "Disputes are handled manually by the admin team.",
      section5Item3: "In cases of chargebacks, the platform reserves the right to deduct from the relevant creator's balance.",
      section6Title: "6. Suspension",
      section6Content: "YourPage reserves the right to suspend or delete accounts that violate these terms without prior notice.",
      section7Title: "7. Changes to Terms",
      section7Content: "YourPage may update these terms and conditions at any time. Changes will be announced through the platform.",
    },
    privacy: {
      section1Title: "1. Data We Collect",
      section1Item1: "Account: Email, username, password (encrypted).",
      section1Item2: "Profile: Display name, bio, avatar (optional).",
      section1Item3: "KYC: Full name, ID number, ID photo (only for withdrawal verification).",
      section1Item4: "Transactions: Purchase, donation, and withdrawal history.",
      section2Title: "2. How We Use Data",
      section2Item1: "Providing and improving platform services.",
      section2Item2: "Processing transactions and payments.",
      section2Item3: "Identity verification for fund withdrawals.",
      section2Item4: "Sending account and transaction notifications.",
      section3Title: "3. Data Protection",
      section3Item1: "Email is never displayed on public pages.",
      section3Item2: "Passwords are stored as hashes (bcrypt).",
      section3Item3: "ID data can only be accessed by admins for verification.",
      section3Item4: "JWTs only contain user ID and role \u2014 no personal data.",
      section3Item5: "All connections use HTTPS in production.",
      section4Title: "4. Storage",
      section4Item1: "Data is stored on servers located in Indonesia.",
      section4Item2: "Media files are stored in encrypted object storage.",
      section4Item3: "Data is not sold or shared with third parties.",
      section5Title: "5. User Rights",
      section5Item1: "You may modify or delete your profile data at any time.",
      section5Item2: "To delete your account, please contact the admin.",
      section6Title: "6. Contact",
      section6Item1: "Privacy-related questions can be sent to the admin through the platform.",
    },
  },
  statusPage: {
    title: "YourPage Status",
    allNormal: "All Systems Normal",
    disruption: "Service Disruption",
    website: "Website",
    api: "API",
    database: "Database",
    autoRefresh: "Auto-refreshes every 30 seconds",
  },
  offlinePage: {
    title: "You\u2019re Offline",
    description: "Please check your internet connection and try again.",
    retry: "Try Again",
  },
  overlayAlerts: {
    missingIdTitle: "Incomplete Overlay URL",
    missingIdDesc: "Add ?id=<creator-id> to the URL. Copy the full URL from Dashboard → Overlay.",
    ttsDonate: "{name} donated {amount} credit",
    defaultGoalTitle: "Donation Goal",
    goalProgress: "{current} of {target}",
    anonymous: "Anonymous",
  },
  adminOverview: {
    panelLabel: "Admin Panel",
    dashboardLabel: "Dashboard",
    allProcessed: "All done! 🎉",
    topupLabel: "Top-up {amount} → {credits} Credit",
    viewProof: "View proof",
    approve: "Approve",
    reject: "Reject",
    rejectTopupTitle: "Reject Top-up?",
    rejectTopupMessage: "Are you sure you want to reject this top-up?",
    withdrawalLabel: "Withdrawal {amount}",
    rejectWithdrawalTitle: "Reject Withdrawal?",
    rejectWithdrawalMessage: "Are you sure you want to reject this withdrawal?",
    kycLabel: "KYC: {name}",
    kycApproved: "KYC approved",
    rejectKycTitle: "Reject KYC?",
    rejectKycMessage: "Are you sure you want to reject {name}'s KYC?",
    rejectConfirmLabel: "Reject",
    revenueSection: "Revenue",
    gmv: "GMV",
    revenueFee: "Revenue (Fee)",
    donations: "Donations",
    withdrawn: "Withdrawn",
    platformSection: "Platform",
    users: "Users",
    creators: "Creators",
    posts: "Posts",
    products: "Products",
    reports: "Reports",
    reportsPending: "{count} pending",
    linkUsers: "Users",
    linkPayments: "Payments",
    linkReports: "Reports",
    linkProfit: "Profit",
    breadcrumbAdmin: "Admin",
    breadcrumbUsers: "Users",
    userListTitle: "Users",
    addUserFinance: "Finance User",
    financeUserTitle: "Add Finance User",
    createFinanceUser: "Create Finance User",
    searchPlaceholder: "Search username, name...",
    noUsers: "No users found.",
    userDetailTitle: "User Detail",
    userId: "ID:",
    joined: "Joined:",
    bio: "Bio:",
    viewPage: "View Page",
    banUser: "Ban User",
    unbanUser: "Unban",
    bannedBadge: "Banned",
    banConfirmTitle: "Ban User?",
    banConfirmMessage: "Are you sure you want to ban {name}?",
    promoCreatorTitle: "Creator Promo",
    promoFeePercent: "Promo Fee %",
    promoFeePlaceholder: "Leave blank = use tier",
    promoDurationDays: "Duration (days)",
    featuredHomepage: "Featured on homepage",
    adminNoteOptional: "Admin note (optional)",
    savePromo: "Save Promo",
    resetPromo: "Reset Promo",
    paymentHistoryTitle: "Payment History ({count})",
    donationHistoryTitle: "Donation History ({count})",
    noPayments: "No payments.",
    noDonations: "No donations.",
    adminProfileTitle: "Admin Profile",
    profileCardTitle: "Profile",
    settingsTitle: "Platform Settings",
    configuration: "Configuration",
    platformFeePercent: "Platform Fee (%)",
    minWithdrawalIdr: "Min Withdrawal (IDR)",
    creditRateIdr: "Credit Rate (IDR per credit)",
    saving: "Saving...",
    save: "Save",
    qrisPlatform: "QRIS Platform",
    qrisDescription: "QRIS image shown to users during manual top-up.",
    noQris: "No QRIS yet",
    uploadNewQris: "Upload New QRIS",
    uploading: "Uploading...",
    uploadFailed: "Upload failed",
    paymentMethods: "Top-up Payment Methods",
    qrisManual: "QRIS Manual",
    qrisManualDesc: "Users transfer via QRIS, upload proof, admin verifies manually.",
    enableQris: "Enable QRIS",
    qrisUploadWarning: "⚠ Upload a QRIS image first so users can scan.",
    stripeCard: "Stripe (Card)",
    stripeDesc: "Automatic card payments via Stripe Checkout. Credits added instantly.",
    enableStripe: "Enable Stripe",
    stripeConfiguration: "Stripe Configuration",
    publishableKey: "Publishable Key",
    secretKey: "Secret Key",
    webhookSecret: "Webhook Signing Secret",
    webhookEndpoint: "Webhook endpoint",
    keySecurityNote: "Keys are stored securely — the API only shows the last 4 characters. Re-enter only if you need to change them.",
    showSecret: "Show",
    hideSecret: "Hide",
    savePaymentMethods: "Save Payment Methods",
    settingsSaved: "Settings saved!",
    paymentMethodsSaved: "Payment methods saved!",
    settingsSaveFailed: "Failed to save",
  },
  monetization: {
    donationSettingsTitle: "Donation Settings",
    donationGoalTitle: "Donation Goal",
    donationGoalDesc: "Show a donation goal on your page to motivate supporters.",
    goalTitleLabel: "Goal Title",
    goalTitlePlaceholder: "e.g., New camera for better content 📸",
    goalAmountLabel: "Goal Amount",
    goalAmountPlaceholder: "Target (Credit)",
    creditUnit: "Credit",
    goalCollected: "{amount} collected",
    goalTargetLabel: "target",
    goalPercentReached: "{percent}% reached",
    preset500Credit: "500 Credit",
    preset1kCredit: "1K Credit",
    preset5kCredit: "5K Credit",
    welcomeMessageTitle: "Welcome Message",
    welcomeMessageDesc: "Auto-reply message shown after someone donates or purchases your product.",
    welcomeMessagePlaceholder: "e.g., Thank you so much for your support! 🙏 You're the best. Check out my exclusive content in the Posts tab!",
    saving: "Saving...",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved!",
    saveFailed: "Failed",
    chatSettingsTitle: "Chat Settings",
    chatPriceTitle: "Chat Price",
    chatPriceLabel: "Price per message (Credits)",
    chatPricePlaceholder: "0 = free",
    freeChatNote: "Free chat — all supporters can send messages at no cost.",
    simulationTitle: "Per-message simulation:",
    simulationSenderPays: "Sender pays",
    simulationYouGet: "You get",
    simulationFee: "Fee ({percent}%)",
    preset5Credit: "5 Credit",
    preset10Credit: "10 Credit",
    preset25Credit: "25 Credit",
    presetFree: "Free",
    whoCanChatTitle: "Who Can Chat",
    whoCanChatDesc: "Set who can start conversations with you.",
    chatOptionAllLabel: "👥 Everyone",
    chatOptionAllDesc: "Supporters & creators",
    chatOptionSupporterLabel: "🙋 Supporters Only",
    chatOptionSupporterDesc: "Supporters only",
    chatOptionCreatorLabel: "🎨 Creators Only",
    chatOptionCreatorDesc: "Creators only",
    chatOptionNoneLabel: "🔕 None",
    chatOptionNoneDesc: "Chat disabled",
    chatDisabledWarning: "⚠️ No one can start a new chat with you.",
    autoReplyTitle: "🤖 Auto-Reply",
    businessBadgeLabel: "Business",
    autoReplyDesc: "Auto-reply message sent when a supporter sends their first chat.",
    autoReplyPlaceholder: "e.g., Thanks for reaching out! I'll get back to you soon 😊",
    autoReplyActive: "✅ Auto-reply active",
    upgradeToBusiness: "Upgrade to Business to enable auto-reply.",
    upgradeButton: "Upgrade",
    chatLimitsTitle: "📊 Chat Limits",
    dailyReplies: "Daily replies",
    dailyRepliesUnlimited: "Unlimited",
    dailyRepliesLimited: "10 / day",
    senderRequirement: "Sender requirement",
    mustFollow: "Must follow you",
    yourFeeTier: "Your fee tier",
    chatSettingsSaved: "Chat settings saved!",
    chatSaveFailed: "Failed to save",
    membershipTitle: "Fan Membership",
    activeMembers: "Active Members",
    tierCountLabel: "Tiers",
    membershipTiersLabel: "Membership Tiers",
    creditPerMonth: "Credits/month",
    deleteTierTitle: "Delete Tier?",
    deleteTierMessage: "Are you sure you want to delete tier \"{name}\"?",
    deleteConfirmLabel: "Delete",
    noTiersYet: "No tiers yet. Create one on the right →",
    createNewTier: "Create New Tier",
    tierNameLabel: "Tier Name",
    tierNamePlaceholder: "Bronze, Silver, Gold",
    tierPriceLabel: "Price (Credits/month)",
    tierPricePlaceholder: "10",
    tierDescriptionLabel: "Description",
    tierDescriptionPlaceholder: "Short description",
    tierPerksPlaceholder: "Perks (e.g., Exclusive post access, Priority chat)",
    creating: "Creating...",
    createTierButton: "Create Tier",
    tierCreated: "Tier created!",
    tierDeleted: "Tier deleted",
    deleteTierFailed: "Failed to delete tier",
    salesTitle: "Sales",
    netRevenue: "Net Revenue",
    postLabel: "Post",
    productLabel: "Product",
    donationLabel: "Donation",
    colType: "Type",
    colBuyer: "Buyer",
    colGross: "Gross",
    colNet: "Net",
    colDate: "Date",
    noSalesTitle: "No sales yet",
    noSalesDesc: "Create paid content to start earning",
    breadcrumbDashboard: "Dashboard",
    breadcrumbWithdrawals: "Withdrawals",
    withdrawalsTitle: "Withdraw Funds",
    withdrawButtonLabel: "💰 Withdraw Funds",
    creditBalanceLabel: "Credit Balance",
    totalEarningsLabel: "Total Earnings",
    withdrawalFormTitle: "Withdrawal Form",
    amountLabel: "Credit Amount (min {min})",
    amountPlaceholder: "100",
    amountEquivalent: "= Rp {amount}",
    bankNamePlaceholder: "Bank Name (BCA, BNI, Mandiri, etc.)",
    accountNumberPlaceholder: "Account Number (10-16 digits)",
    confirmAccountPlaceholder: "Confirm Account Number",
    accountNamePlaceholder: "Account Holder Name (as per ID)",
    accountMismatch: "Account numbers do not match",
    processing: "Processing...",
    submitRequest: "Submit Request",
    validationDigitsError: "Account number must be 10-16 digits",
    minimumWithdrawal: "Minimum withdrawal {min} Credits",
    insufficientBalance: "Insufficient balance",
    kycRequired: "KYC must be verified first",
    noWithdrawals: "No withdrawals yet",
    adminNote: "Admin: {note}",
  },
  welcomePage: {
    title: "Welcome! \uD83C\uDF89",
    accountCreated: "Your account has been created. Here\u2019s what you can do:",
    creator: {
      createPost: "Create Your First Post",
      createPostDesc: "Write free or paid content for your fans.",
      uploadProduct: "Upload Digital Products",
      uploadProductDesc: "Sell e-books, presets, templates, and more.",
      receiveDonation: "Receive Donations",
      receiveDonationDesc: "Fans can send donations directly to your page.",
    },
    supporter: {
      findCreators: "Discover Creators",
      findCreatorsDesc: "Search and follow your favorite creators.",
      topupCredit: "Top-up Credits",
      topupCreditDesc: "Add funds to buy content and send donations.",
      buyContent: "Buy Content",
      buyContentDesc: "Access exclusive content from creators.",
    },
    openDashboard: "Open Dashboard",
  },
  contentMgr: {
    // Posts
    postsTitle: "Posts",
    postsPublishedCount: "{count} published",
    postsDraftCount: "{count} draft",
    createPost: "Create Post",
    close: "Close",
    postTitlePlaceholder: "Post title",
    postContentPlaceholder: "Write content...",
    uploadMedia: "Upload Media",
    accessLabel: "Access",
    free: "Free",
    paid: "Paid",
    members: "Members",
    priceCredit: "Price (Credits)",
    pricePlaceholder: "5",
    previewText: "Preview text",
    teaserPlaceholder: "Short teaser...",
    tierMinimum: "Minimum tier",
    allMembers: "All Members",
    creditPerMonth: "{count} Credits/month",
    noMembershipTier: "⚠️ No membership tier yet.",
    createTierFirst: "Create one first",
    scheduleOptional: "Schedule (optional)",
    saving: "Saving...",
    schedule: "📅 Schedule",
    publish: "🚀 Publish",
    draftHeader: "📝 Drafts ({count})",
    emptyPostsTitle: "No posts yet",
    emptyPostsDesc: "Create your first post!",
    deletePostTitle: "Delete Post?",
    deletePostMessage: "Deleted posts cannot be restored.",
    postCreated: "Post published successfully!",
    postCreatedFailed: "Failed to create post",
    postDeleted: "Post deleted",
    // Post editor
    back: "Back",
    editPost: "Edit Post",
    postTitleLabel: "Title",
    excerptOptional: "Excerpt (optional)",
    contentLabel: "Content...",
    membersOnly: "Members Only",
    selectTierMinimum: "Select minimum tier (blank = all members)",
    publishedStatus: "✓ Published",
    draftStatus: "Draft",
    save: "Save",
    postSaved: "Post saved!",
    saveFailed: "Failed to save",
    mediaCount: "Media ({count})",
    upload: "Upload",
    noMedia: "No media yet.",
    publishedBadge: "Published",
    draftBadge: "Draft",
    // Products
    productsTitle: "Product Catalog",
    productsCount: "{count} products",
    productsSoldCount: "{count} sold",
    createProduct: "Create Product",
    productName: "Name",
    productNamePlaceholder: "Product name",
    slug: "Slug",
    slugPlaceholder: "url-friendly",
    descriptionPlaceholder: "Product description...",
    typeLabel: "Type",
    ebook: "📖 E-book",
    preset: "🎨 Preset",
    template: "📄 Template",
    other: "📦 Other",
    deliveryLabel: "Delivery",
    fileDelivery: "📁 Digital File",
    linkDelivery: "🔗 Link / Key",
    deliveryUrlPlaceholder: "Course URL, license key, invite link",
    thumbnail: "Thumbnail",
    productFiles: "Product Files",
    saveProduct: "Save Product",
    deleteProductTitle: "Delete Product?",
    deleteProductMessage: "Deleted products cannot be restored.",
    productCreated: "Product created successfully!",
    productCreatedFailed: "Failed to create product",
    emptyProductsTitle: "No products yet",
    emptyProductsDesc: "Create your first digital product!",
    // Product editor
    editProduct: "Edit Product",
    activeStatus: "✓ Active",
    inactiveStatus: "Inactive",
    deliveryTypeLabel: "Delivery Type",
    urlSerialKey: "URL / Serial Key",
    urlSerialKeyPlaceholder: "https://... or serial key",
    productSaved: "Product saved!",
    productSaveFailed: "Failed to save product",
    saved: "Saved!",
    assetFilesCount: "Product Files ({count})",
    uploadFile: "Upload File",
    noAssets: "No files yet.",
    noAssetsDesc: "Upload the files buyers will receive.",
  },
  adminModeration: {
    // Common
    approve: "Approve",
    reject: "Reject",
    delete: "Delete",
    ban: "Ban",
    view: "View",
    close: "Close",
    // Status badges
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    statusResolved: "Resolved",
    statusDismissed: "Dismissed",
    statusPaid: "Paid",
    statusFailed: "Failed",
    statusActive: "Active",
    statusInactive: "Inactive",
    // Filter labels
    filterPending: "Pending",
    filterApproved: "Approved",
    filterRejected: "Rejected",
    filterPaid: "Paid",
    filterFailed: "Failed",
    filterResolved: "Resolved",
    filterDismissed: "Dismissed",
    // Sort labels
    sortTitle: "Title",
    sortViews: "Views",
    sortLikes: "Likes",
    sortComments: "Comments",
    sortDate: "Date",
    sortName: "Name",
    sortPrice: "Price",
    sortSales: "Sales",
    sortType: "Type",
    sortStatus: "Status",
    sortAmount: "Amount",
    sortDonor: "Donor",
    sortReason: "Reason",
    // Search placeholders
    searchPosts: "Search titles, creators...",
    searchProducts: "Search product names, types...",
    searchDonations: "Search donors, creators...",
    searchKyc: "Search names, user IDs...",
    searchReports: "Search reasons, targets...",
    // Page titles
    postsTitle: "Posts",
    productsTitle: "Products",
    donationsTitle: "Donations",
    kycTitle: "KYC Verification",
    reportsTitle: "Content Reports",
    promoTitle: "Promo & Creator Partnerships",
    announcementsTitle: "Platform Announcements",
    // Empty states
    emptyPosts: "No posts.",
    emptyProducts: "No products.",
    emptyDonations: "No donations.",
    emptyKyc: "No KYC submissions.",
    emptyReports: "No reports.",
    // Posts page
    postDeleteTitle: "Delete Post?",
    postDeleteMessage: 'Are you sure you want to delete "{name}"?',
    // Products page
    productSold: "sold",
    productInactive: "Inactive",
    productDeleteTitle: "Delete Product?",
    productDeleteMessage: 'Are you sure you want to delete "{name}"?',
    // Donations page
    donationFrom: "From:",
    donationTo: "To:",
    donationNet: "Net:",
    donationPayment: "Payment:",
    donationDate: "Date:",
    donationAnonymous: "Anonymous",
    // KYC page
    kycUser: "User:",
    kycSubmitted: "Submitted:",
    kycReviewed: "Reviewed:",
    kycDocAlt: "Identity document for {name}",
    kycDocClickHint: "Click to enlarge · link expires in 15 minutes",
    kycDocUnavailable: "Document not available. Ask the user to re-upload before approving.",
    kycNoteLabel: "Note:",
    kycNotePlaceholder: "Notes (optional)",
    kycRejectTitle: "Reject KYC?",
    kycRejectMessage: "Are you sure you want to reject {name}'s KYC?",
    // Reports page
    reportTarget: "Target:",
    reportReporter: "Reporter:",
    reportDate: "Date:",
    reportNotePlaceholder: "Admin notes (optional)",
    reportResolve: "Resolve",
    reportDismiss: "Dismiss",
    reportBanTitle: "Ban User?",
    reportBanMessage: "Are you sure you want to ban this user?",
    reportBanUser: "Ban User",
    reportDeleteTitle: "Delete {type}?",
    reportDeleteMessage: "Are you sure you want to delete this content?",
    // Promo page
    promoTotalCreator: "Total Creators",
    promoFeatured: "Featured",
    promoTierAvailable: "Tiers Available",
    promoVerified: "Verified",
    promoFeaturedCreators: "Featured Creators",
    promoFollowers: "followers",
    promoEditPromo: "Edit Promo",
    promoEmptyFeatured: "No featured creators yet. Set on the user detail page.",
    promoAllCreators: "All Creators",
    promoSetPromo: "Set Promo",
    promoTierPricing: "Tier Pricing",
    promoFree: "Free",
    promoPerMonth: "/month",
    // Announcements page
    announcementsCreateTitle: "Create New Announcement",
    announcementsTitlePlaceholder: "Announcement title",
    announcementsBodyPlaceholder: "Announcement body...",
    announcementsAllUsers: "All Users",
    announcementsOnlyCreator: "Creators Only",
    announcementsOnlySupporter: "Supporters Only",
    announcementsExpiryPlaceholder: "Expires (optional)",
    announcementsPublish: "Publish",
    announcementsEmpty: "No announcements yet.",
    announcementsActive: "Active",
    announcementsInactive: "Inactive",
    announcementsExpiresLabel: "Expires:",
    announcementsDeleted: "Announcement deleted",
    announcementsDeleteFailed: "Failed to delete",
    announcementsValidation: "Title and body are required",
    announcementsCreated: "Announcement created!",
    announcementsCreateFailed: "Failed to create announcement",
  },
  accountMgr: {
    // subscription
    subscriptionTitle: "Subscription",
    subscriptionActiveUntil: "Tier active until: {date}",
    subscriptionActive: "Active",
    subscriptionFree: "Free",
    subscriptionCreditPerMonth: "Credits/month",
    subscriptionFeeLabel: "Fee",
    subscriptionStorageLabel: "Storage",
    subscriptionCurrentPlan: "Current Plan",
    subscriptionDowngrade: "Downgrade",
    subscriptionUpgrade: "Upgrade",
    subscriptionUpdated: "Tier updated successfully!",
    subscriptionFailed: "Failed to subscribe",
    subscriptionDowngradeTitle: "Downgrade to Free?",
    subscriptionUpgradeTitle: "Upgrade to {name}?",
    subscriptionDowngradeDesc: "The fee will return to {fee}% and the product limit to {limit}.",
    subscriptionUpgradeDesc: "{value} Credits will be deducted from your wallet for 1 month.",
    subscriptionPayUpgrade: "Pay & Upgrade",
    // kyc
    kycTitle: "KYC Verification",
    kycStatusPending: "Pending Review",
    kycStatusApproved: "Approved",
    kycStatusRejected: "Rejected",
    kycNote: "Note: {note}",
    kycReviewing: "The admin is reviewing your documents.",
    kycApproved: "KYC verified. You can now make withdrawals.",
    kycRejected: "Contact admin to resubmit.",
    kycUploadTitle: "Upload ID (KTP)",
    kycUploadDesc: "Required for your first withdrawal. Your data is safe and never shown publicly.",
    kycFullNameLabel: "Full Name (as on ID)",
    kycFullNamePlaceholder: "Full name",
    kycIdNumberLabel: "ID Number (16 digits)",
    kycIdNumberPlaceholder: "3201234567890001",
    kycDigitCount: "{count}/16 digits",
    kycPhotoLabel: "ID Photo",
    kycPhotoSelect: "Choose ID photo",
    kycSubmitting: "Sending...",
    kycSubmitButton: "Submit KYC",
    kycFailed: "Failed to submit KYC",
    // tax
    taxTitle: "Tax Report",
    taxLockedDesc: "This feature is available on Pro and Business tiers.",
    taxUpgradeNow: "Upgrade Now",
    taxSummaryTitle: "2026 Summary",
    taxGrossRevenue: "Gross Revenue",
    taxPlatformFee: "Platform Fee ({fee}%)",
    taxNetEarnings: "Net Earnings",
    taxEstimationNote: "* Estimate based on total earnings. For a per-transaction breakdown, use Export CSV on the Analytics page.",
    taxDisclaimer: "Note: YourPage does not withhold taxes. Creators are responsible for reporting their own taxes in accordance with applicable regulations.",
    // referral
    referralTitle: "Referral Program 🎁",
    referralSubtitle: "Invite friends to sign up and earn credit bonuses for both of you.",
    referralTotalLabel: "Total Referrals",
    referralCreditsEarnedLabel: "Total Credits Earned",
    referralBonusLabel: "Bonus per Referral",
    referralLinkTitle: "Your Referral Link & Code",
    referralLoading: "Loading...",
    referralCommissionDesc: "Everyone who signs up through your link/code gets {value} credit bonus, and you get the same too.",
    referralRegisteredTitle: "Signed Up via Your Referral",
    referralEmpty: "No one has signed up yet. Share your link!",
    referralLinkCopied: "Referral link copied!",
    referralCodeCopied: "Referral code copied!",
    // feed
    feedTitle: "Feed",
    feedExploreLink: "Explore Creators →",
    feedLoadError: "Failed to load feed.",
    feedRetry: "Try again",
    feedEmptyTitle: "Feed is empty",
    feedEmptyDesc: "Follow other creators to see their content",
    feedExploreCta: "Explore Creators",
    // overlay
    overlayTitle: "OBS Overlay",
    overlaySubtitle: "Add the URLs below as a Browser Source in OBS. Alerts appear automatically as soon as a donation comes in.",
    overlayBrowserSourceUrl: "Browser Source URL",
    overlayBrowserSourceDesc: "One URL per widget. Check 'Refresh browser when scene becomes active' in OBS.",
    overlayDonationAlert: "Donation alert",
    overlayDonationGoal: "Donation goal",
    overlayCopy: "Copy",
    overlaySending: "Sending...",
    overlayTestAlert: "Send test alert",
    overlayTestDesc: "Open the overlay in OBS or another tab, then click this to preview the result without waiting for a real donation.",
    overlayAppearanceTitle: "Appearance",
    overlayAppearanceDesc: "Applies to all donation alerts.",
    overlayAnimationLabel: "Entrance animation",
    overlayPositionLabel: "Screen position",
    overlayAccentColor: "Accent color",
    overlayTextColor: "Text color",
    overlayFont: "Font",
    overlayDurationLabel: "Display duration: {value} sec",
    overlayDurationAria: "Alert display duration",
    overlayAlertTextLabel: "Alert text",
    overlayAlertTextHint: "Use {donor} for the supporter's name and {amount} for the credit amount.",
    overlayPreview: "Preview",
    overlaySoundTitle: "Sound",
    overlaySoundDesc: "Sound is chosen from the tier that matches the donation amount.",
    overlayVolumeLabel: "Volume: {value}%",
    overlayVolumeAria: "Alert sound volume",
    overlayReadMessage: "Read donation message",
    overlayReadMessageDesc: "Supporter messages are read out automatically via text-to-speech.",
    overlayTtsAria: "Enable text-to-speech",
    overlayTtsMinLabel: "Minimum credits to read aloud",
    overlayTtsMinHint: "Donations below this value still show, but are not read aloud.",
    overlayTierTitle: "Alert tiers",
    overlayTierDesc: "Different images and sounds based on donation size. The highest matching tier is used.",
    overlayNoLabel: "No label",
    overlayHasSound: "has sound",
    overlayNoSound: "no sound",
    overlayDeleteTier: "Delete tier {min} credit",
    overlayEmptyTiers: "No tiers yet. Add one below.",
    overlayMinCredits: "Minimum credits",
    overlayLabel: "Label",
    overlayLabelPlaceholder: "Super Donator",
    overlayChangeImage: "Change image",
    overlaySelectImage: "Choose image / GIF",
    overlaySelectSound: "Choose sound",
    overlayUploading: "Uploading...",
    overlayAddTier: "Add tier",
    overlaySaving: "Saving...",
    overlaySaveSettings: "Save settings",
    overlayTierAdded: "Tier added",
    overlayTierAddFailed: "Failed to add tier",
    overlayTierDeleted: "Tier deleted",
    overlaySettingsSaved: "Settings saved",
    overlaySettingsFailed: "Failed to save",
    overlayTestSent: "Test alert sent to overlay",
    overlayTestFailed: "Failed to send test alert",
    overlayUrlCopied: "URL copied",
    animBounce: "Bounce",
    animBounceHint: "Bounces up from below",
    animSlide: "Slide",
    animSlideHint: "Slides in from the side",
    animFade: "Fade",
    animFadeHint: "Fades in slowly",
    animSpin: "Spin",
    animSpinHint: "Spins in",
    animDrop: "Drop",
    animDropHint: "Drops from above",
    animPop: "Pop",
    animPopHint: "Pops in place",
    posTopLeft: "Top left",
    posTop: "Top",
    posTopRight: "Top right",
    posCenter: "Center",
    posBottomLeft: "Bottom left",
    posBottom: "Bottom",
    posBottomRight: "Bottom right",
  },
  adminFinance: {
    paymentsTitle: "Payments",
    exportCsv: "📥 Export CSV",
    filterPending: "Pending",
    filterPaid: "Paid",
    filterFailed: "Failed",
    filterRefunded: "Refunded",
    filterApproved: "Approved",
    filterProcessed: "Processed",
    filterRejected: "Rejected",
    sortAmount: "Amount",
    sortProvider: "Provider",
    sortUsecase: "Usecase",
    sortDate: "Date",
    sortStatus: "Status",
    sortCredits: "Credits",
    sortDonor: "Donor",
    sortBank: "Bank",
    sortNominal: "Nominal",
    sortEvent: "Event",
    sortTanggal: "Date",
    searchPaymentsPlaceholder: "Search payer, provider...",
    searchAuditPlaceholder: "Search event, method, actor...",
    searchTopupsPlaceholder: "Search donor name, user ID...",
    searchWithdrawalsPlaceholder: "Search bank, account name...",
    paymentCode: "Code: {code}",
    labelProvider: "Provider:",
    labelUsecase: "Usecase:",
    labelFee: "Fee:",
    labelNet: "Net:",
    labelPayer: "Payer:",
    refundReasonPlaceholder: "Refund reason",
    refundButton: "Refund",
    editStatus: "Edit Status",
    emptyPayments: "No payments found.",
    auditTitle: "Payment Audit Trail",
    auditSubtitle: "Permanent record of every money and credit movement — who, when, how much, from which IP.",
    labelAktor: "Actor:",
    labelCredit: "Credit:",
    labelRef: "Ref:",
    labelWaktu: "Time:",
    emptyAudit: "No payment audit records yet.",
    filterTopupCreated: "Top-up created",
    filterTopupPaid: "Top-up paid",
    filterTopupApproved: "Top-up approved",
    filterTopupRejected: "Top-up rejected",
    filterCheckoutPost: "Post purchase",
    filterCheckoutProduct: "Product purchase",
    filterDonation: "Donation",
    filterPaymentRefunded: "Refund",
    filterWithdrawalStatusChanged: "Withdrawal",
    eventTopupCreated: "Top-up created",
    eventTopupPaid: "Top-up paid",
    eventTopupApproved: "Top-up approved",
    eventTopupRejected: "Top-up rejected",
    eventCheckoutPost: "Post purchase",
    eventCheckoutProduct: "Product purchase",
    eventCheckoutDonation: "Donation",
    eventCheckoutChat: "Paid chat",
    eventPaymentRefunded: "Refund",
    eventWithdrawalRequested: "Withdrawal requested",
    eventWithdrawalStatusChanged: "Withdrawal status",
    roleUser: "User",
    roleAdmin: "Admin",
    roleFinance: "Finance",
    roleSystem: "System",
    topupTitle: "Top-up Credit",
    breadcrumbAdmin: "Admin",
    breadcrumbTopup: "Top-up",
    selectedCount: "selected",
    approveAll: "✅ Approve All",
    rejectAllTitle: "Reject All?",
    rejectAllMessage: "Are you sure you want to reject {count} top-ups?",
    rejectAllConfirm: "Reject All",
    selectAllPending: "Select all pending ({count})",
    labelDonor: "Donor:",
    labelUser: "User:",
    labelUniqueCode: "Unique Code:",
    labelTanggal: "Date:",
    notePlaceholder: "Note (optional)",
    approveButton: "Approve",
    rejectButton: "Reject",
    rejectTopupTitle: "Reject Top-up?",
    rejectTopupMessage: "Are you sure you want to reject top-up {amount}?",
    processing: "Processing...",
    notePrefix: "Note: {note}",
    emptyTopups: "No top-ups found.",
    topupApprovedToast: "{count} topup approved",
    topupRejectedToast: "{count} topup rejected",
    withdrawalsTitle: "Withdrawals",
    labelNoRek: "Acct No:",
    labelNama: "Name:",
    labelCreator: "Creator:",
    markProcessed: "Mark Processed",
    rejectWithdrawalTitle: "Reject Withdrawal?",
    rejectWithdrawalMessage: "Are you sure you want to reject withdrawal {amount}?",
    withdrawalApprovedToast: "{count} withdrawal approved",
    withdrawalRejectedToast: "{count} withdrawal rejected",
    emptyWithdrawals: "No withdrawals found.",
    profitTitle: "Platform Profit",
    totalRevenue: "Total Revenue (Fee)",
    totalWithdrawn: "Withdrawn",
    availableToWithdraw: "Available to Withdraw",
    withdrawProfitTitle: "Withdraw Profit",
    nominalPlaceholder: "Amount (IDR)",
    bankNamePlaceholder: "Bank Name",
    accountNumberPlaceholder: "Account Number",
    accountNamePlaceholder: "Account Holder Name",
    optionalNotePlaceholder: "Note (optional)",
    withdrawButtonLabel: "Withdraw",
    withdrawalHistoryTitle: "Withdrawal History",
    withdrawRecordedBy: "by {name}",
    withdrawSuccessToast: "Withdrawal recorded successfully!",
    withdrawFailedToast: "Failed",
  },
  compAccount: {
    // change-password
    changePasswordTitle: "🔒 Change Password",
    changePasswordDesc: "Use a strong password that hasn't been used before to protect your account.",
    oldPasswordLabel: "Old Password",
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm Password",
    oldPasswordPlaceholder: "Old password",
    newPasswordPlaceholder: "Min 8 characters",
    confirmPasswordPlaceholder: "Repeat new password",
    passwordMismatch: "Passwords do not match",
    passwordChangeSuccess: "Password changed successfully!",
    passwordChangeFailed: "Failed to change password",
    // auth-guard
    loading: "Loading...",
    // install-prompt
    installTitle: "Install YourPage",
    installDesc: "Faster access directly from your home screen",
    installButton: "Install",
    installLater: "Later",
    // cookie-consent
    cookieMessage: "We use cookies to improve your experience.",
    cookieLearnMore: "Learn more",
    cookieReject: "Reject",
    cookieAccept: "Accept",
    // storage-quota
    storageTitle: "Storage",
    storageUsedOf: "of {quota} used",
    storageAria: "Storage used: {pct} percent of {quota}",
    storageAlmostFull: "Storage almost full ({pct}%).",
    storageUpgradeDesc: "Upgrade your plan to increase your storage capacity.",
    storageUpgradeButton: "Upgrade Plan",
    // password-strength
    ruleMinChars: "Min 8 characters",
    ruleUppercase: "Uppercase letter",
    ruleNumber: "Number",
    ruleSymbol: "Symbol",
    // load-more
    loadingDots: "Loading...",
    loadMore: "Load More",
    // infinite-scroll
    noMore: "No more",
    // confirm-dialog
    confirmYes: "Yes",
    confirmCancel: "Cancel",
  },
  compSocial: {
    // post-card
    paidContent: "Paid content",
    topupCredit: "Top-up Credits",
    processing: "Processing...",
    buy: "Buy {price}",
    writeComment: "Write a comment...",
    failed: "Failed",
    linkCopied: "Link copied!",
    creator: "Creator",
    user: "User",
    // report-button
    reasonNsfw: "NSFW / Inappropriate",
    reasonPlagiarism: "Plagiarism",
    reasonScam: "Scam",
    reasonSpam: "Spam",
    reasonOther: "Other",
    report: "Report",
    reportContent: "Report Content",
    detailOptional: "Details (optional)",
    sending: "Sending...",
    sendReport: "Submit Report",
    reported: "Reported",
    // social-auth-buttons
    connecting: "Connecting...",
    continueWithGoogle: "Continue with Google",
    continueWithFacebook: "Continue with Facebook",
    connectFailed: "Failed to connect to {provider}",
    // content-protection
    contentProtected: "Content is protected",
    // bottom-nav
    bottomHome: "Home",
    bottomChat: "Chat",
    bottomNotifications: "Notifications",
    bottomProfile: "Profile",
    mainNavigation: "Main navigation",
    // dynamic-user-title
    routeDashboard: "Dashboard",
    routeManagePosts: "Manage Posts",
    routeManageProducts: "Manage Products",
    routeSales: "Sales",
    routeDonations: "Donations",
    routeAnalytics: "Analytics",
    routeWithdrawals: "Withdrawals",
    routeCreatorProfile: "Creator Profile",
    routeSubscription: "Subscription",
    routeSupporterDashboard: "Supporter Dashboard",
    routeWallet: "Wallet",
    routeChat: "Messages",
    routeNotifications: "Notifications",
    routeExplore: "Explore Creators",
    routeFeed: "Feed",
    routeCreatorPage: "Creator Page",
    titleDefault: "YourPage — Your page, your earnings",
    titleCreator: "Creator",
    // offline-indicator
    offline: "No internet connection",
  },
};
