import type { TranslationDictionary } from "../types";

export const id: TranslationDictionary = {
  common: {
    save: "Simpan",
    cancel: "Batal",
    delete: "Hapus",
    edit: "Edit",
    back: "Kembali",
    close: "Tutup",
    search: "Cari",
    loading: "Memuat...",
    processing: "Memproses...",
    confirm: "Konfirmasi",
    error: "Terjadi kesalahan",
    success: "Berhasil",
    copied: "Link disalin!",
    copyLink: "Salin Link",
    share: "Bagikan",
    notFound: "Tidak ditemukan",
    empty: "Belum ada data",
    filter: "Filter",
    all: "Semua",
    status: "Status",
    actions: "Aksi",
    retry: "Coba Lagi",
    notFoundTitle: "Halaman Tidak Ditemukan",
    notFoundDesc: "Halaman yang kamu cari tidak ada atau sudah dipindahkan.",
    backToHome: "Kembali ke Beranda",
    errorTitle: "Terjadi Kesalahan",
    errorDesc: "Coba refresh halaman.",
    refresh: "Refresh",
  },
  nav: {
    home: "Beranda",
    explore: "Explore",
    dashboard: "Dashboard",
    wallet: "Wallet",
    chat: "Pesan",
    notifications: "Notifikasi",
    profile: "Profil",
    pricing: "Harga",
    howItWorks: "Cara Kerja",
    login: "Masuk",
    register: "Daftar",
    logout: "Keluar",
    adminPanel: "Admin Panel",
    feed: "Feed",
    lightMode: "Mode Terang",
    darkMode: "Mode Gelap",
    selectLanguage: "Pilih Bahasa",
    closeMenu: "Tutup menu",
    openMenu: "Buka menu",
  },
  hero: {
    badge: "⚡ Satu Link untuk Semua Sumber Penghasilanmu",
    titlePart1: "Terima Donasi, Jual Karya &",
    titleAccent: "Bangun Komunitas",
    titlePart2: "di Satu Link",
    subtitle: "Gantikan 3 platform terpisah dengan satu halaman personal. Terima pembayaran instan dari fans via QRIS, e-wallet, dan Bank Transfer tanpa biaya bulanan.",
    ctaPrimary: "Klaim Link yourpage.id Kamu — Gratis",
    ctaSecondary: "Jelajahi Karya Kreator",
    trustFree: "100% Gratis Selamanya",
    trustSetup: "Setup 2 Menit",
    trustPayment: "Support QRIS & Semua Bank",
    statCredit: "1 Credit",
    statCreditLabel: "= Rp 1.000",
    statFee: "5%",
    statFeeLabel: "Fee Terendah",
    statSetup: "2 Menit",
    statSetupLabel: "Halaman Siap Pasang",
    statPayout: "1x24 Jam",
    statPayoutLabel: "Pencairan Saldo",
  },
  earningsCard: {
    title: "Dashboard Kreator",
    monthlyEarnings: "Pendapatan bulan ini",
    growthLabel: "+18% dari bulan lalu",
    newDonation: "Donasi baru",
    productSold: "Produk terjual",
    illustrationNote: "*Ilustrasi tampilan dashboard",
  },
  compLanding: {
    dashboardTitle: "Dashboard Kreator",
    monthlyEarnings: "Pendapatan bulan ini",
    growthLabel: "+18% dari bulan lalu",
    chartAriaLabel: "Grafik tren pendapatan yang terus naik",
    illustrationNote: "*Ilustrasi tampilan dashboard",
    newDonation: "Donasi baru",
    productSold: "Produk terjual",
    ebookDesign: "E-book Design",
    takesFromEach: "kamu terima dari tiap transaksi",
    youKeepPercent: "Kamu {percent}%",
    platformFeePercent: "Fee platform {percent}%",
    exampleDonation: "Contoh: donasi {amount} masuk \u2192 kamu terima {takeHome}",
  },
  howItWorks: {
    eyebrow: "Gampang Banget",
    title: "Mulai dalam 3 Langkah",
    step1Title: "Klaim Username Pilihanmu",
    step1Desc: "Daftar gratis dan dapatkan alamat personal yourpage.id/c/namamu dalam 2 menit.",
    step2Title: "Unggah Karya & Tentukan Harga",
    step2Desc: "Pasang harga karya digital, atur target donasi, atau kunci postingan eksklusif.",
    step3Title: "Terima Cuan & Tarik ke Rekening",
    step3Desc: "Fans membayar via QRIS/e-wallet lokal, saldo langsung masuk dompet dan siap ditarik ke bank.",
  },
  howItWorksPage: {
    heroTitle: "Cara Kerja YourPage",
    heroSubtitle: "Panduan lengkap untuk kreator dan supporter",
    forCreatorsHeading: "🎨 Untuk Kreator",
    creatorStep1Title: "Daftar Gratis",
    creatorStep1Desc: "Buat akun dengan email, pilih username. Username akan jadi link halaman kamu: yourpage.id/c/username",
    creatorStep2Title: "Atur Profil",
    creatorStep2Desc: "Upload avatar, banner, tulis bio, tambah link media sosial. Paket Pro/Business bisa kustomisasi warna halaman.",
    creatorStep3Title: "Buat Konten & Produk",
    creatorStep3Desc: "Post gratis atau berbayar (set harga dalam Credit). Upload produk digital seperti e-book, preset, atau template.",
    creatorStep4Title: "Set Donasi & Chat",
    creatorStep4Desc: "Atur target donasi dengan progress bar. Set harga chat per pesan (atau gratis). Setup OBS overlay untuk live streaming.",
    creatorStep5Title: "Terima Pembayaran",
    creatorStep5Desc: "Fans beli konten, kirim donasi, dan bayar chat. Semua penghasilan langsung masuk ke wallet Credit kamu.",
    creatorStep6Title: "Cairkan Dana",
    creatorStep6Desc: "Verifikasi identitas (KYC), lalu tarik saldo Credit ke rekening bank kamu. Min 100 Credit = Rp 100.000.",
    forSupportersHeading: "☕ Untuk Supporter",
    supporterStep1Title: "Daftar & Top-up",
    supporterStep1Desc: "Buat akun supporter. Top-up saldo Credit secara instan via QRIS (1 Credit = Rp 1.000).",
    supporterStep2Title: "Explore Kreator",
    supporterStep2Desc: "Temukan kreator favorit di halaman Explore. Follow mereka untuk update konten terbaru di Feed kamu.",
    supporterStep3Title: "Beli & Dukung",
    supporterStep3Desc: "Buka post atau produk eksklusif, kirim saweran donasi dengan pesan, atau chat privat langsung dengan kreator.",
    supporterStep4Title: "Akses Selamanya",
    supporterStep4Desc: "Konten dan file yang sudah dibeli tersimpan aman dan bisa kamu akses selamanya di menu Library.",
    feeHeading: "💰 Struktur Fee",
    thTier: "Tier",
    thPrice: "Harga",
    thFee: "Fee",
    thCreatorKeeps: "Kreator Dapat",
    freePrice: "Gratis",
    proPrice: "Rp 49.000/bln",
    businessPrice: "Rp 149.000/bln",
    faqHeading: "❓ FAQ",
    faq1Q: "Apakah benar-benar gratis?",
    faq1A: "Ya! Pendaftaran 100% gratis tanpa biaya bulanan tersembunyi. Biaya platform hanya dipotong saat ada transaksi yang berhasil.",
    faq2Q: "Berapa lama pencairan dana?",
    faq2A: "Pencairan dana diproses dalam 1x24 jam kerja langsung ke rekening bank lokal yang kamu daftarkan.",
    faq3Q: "Apakah konten yang dibeli bisa hilang?",
    faq3A: "Tidak. Semua konten dan produk digital yang telah dibeli akan tersimpan selamanya di Library akun supporter kamu.",
    faq4Q: "Bagaimana sistem Credit?",
    faq4A: "1 Credit bernilai tetap Rp 1.000. Top-up via QRIS, gunakan untuk membeli konten atau donasi, dan cairkan ke rekening kapan saja.",
    ctaButton: "Mulai Sekarang — Gratis",
  },
  features: {
    eyebrow: "Semua Ada di Sini",
    title: "Semua Cara Hasilkan Uang di Satu Link",
    subtitle: "Kamu sudah buat konten bagus. Saatnya dihargai.",
    paidPostsTitle: "Post Berbayar",
    paidPostsDesc: "Kunci postingan spesial. Fans bayar 1-klik untuk membaca artikel, komik, atau tutorialmu.",
    digitalProductsTitle: "Produk Digital",
    digitalProductsDesc: "Jual e-book, preset, template, dan materi digital dengan pengiriman file otomatis 24 jam.",
    donationsTitle: "Donasi & Target Goal",
    donationsDesc: "Kumpulkan apresiasi penggemar dengan progress bar target yang transparan dan memotivasi.",
    paidChatTitle: "Chat Berbayar",
    paidChatDesc: "Hargai waktumu dengan menetapkan tarif per pesan untuk sesi konsultasi atau sapaan personal.",
    obsOverlayTitle: "OBS Stream Overlay",
    obsOverlayDesc: "Tampilkan pop-up animasi keren, efek suara lucu, dan GIF saat live streaming.",
    secureContentTitle: "Keamanan Konten",
    secureContentDesc: "Bebas pembajakan dengan proteksi link unduhan aman, watermark otomatis, dan anti-screenshot.",
    analyticsTitle: "Analitik Lengkap",
    analyticsDesc: "Pantau produk paling laris, supporter paling loyal, dan tren pendapatan bulananmu.",
    customPageTitle: "Halaman Personal",
    customPageDesc: "Kustomisasi warna aksen, foto header, dan tautan sosial media agar halaman tampak profesional.",
  },
  feeTransparency: {
    eyebrow: "Transparan 100%",
    title: "Fee Rendah. Sisanya Buat Kamu.",
    subtitle: "Nggak ada biaya tersembunyi. Kamu selalu tahu persis berapa yang kamu bawa pulang dari tiap transaksi.",
    youKeep: "Kamu Bawa Pulang",
    platformFee: "Biaya Platform",
  },
  creditSystem: {
    eyebrow: "Satu Mata Uang",
    title: "Sistem Credit yang Simpel",
    subtitle: "Satu mata uang untuk semua transaksi di YourPage.",
    topupTitle: "Top-up",
    topupDesc1: "Bayar Rp 50.000",
    topupDesc2: "→ Dapat 50 Credit",
    buyContentTitle: "Beli Konten",
    buyContentDesc1: "Post 5 Credit",
    buyContentDesc2: "→ Potong dari wallet",
    donateTitle: "Donasi",
    donateDesc1: "Kirim 10 Credit",
    donateDesc2: "→ Kreator dapat 8–9.5 C",
    withdrawTitle: "Cairkan",
    withdrawDesc1: "Tarik 100 Credit",
    withdrawDesc2: "→ Rp 100.000 ke rekening",
  },
  pricing: {
    eyebrow: "Pilihan Paket",
    title: "Pilih Paket yang Tepat",
    subtitle: "Mulai gratis hari ini, upgrade kapan saja saat kamu berkembang.",
    popularBadge: "Paling Populer",
    freeName: "Free",
    freePrice: "Gratis",
    freeSub: "selamanya",
    freeCta: "Mulai Jualan Gratis",
    proName: "Pro",
    proPrice: "Rp 49.000",
    proSub: "/bulan (49 Credit)",
    proCta: "Pilih Paket Pro",
    businessName: "Business",
    businessPrice: "Rp 149.000",
    businessSub: "/bulan (149 Credit)",
    businessCta: "Pilih Paket Business",
    compareLink: "Lihat perbandingan lengkap semua fitur",
  },
  useCases: {
    eyebrow: "Buat Siapa Saja",
    title: "Cocok untuk Semua Kreator",
    designerTitle: "Desainer & Seniman",
    designerDesc: "Jual preset, template, wallpaper. Upload file, fans download otomatis setelah bayar.",
    educatorTitle: "Edukator & Penulis",
    educatorDesc: "Konten eksklusif, e-book, tips berbayar, dan bangun komunitas loyal.",
    streamerTitle: "Streamer & Gamer",
    streamerDesc: "Terima donasi saat live, overlay OBS kustom, chat santai dengan fans.",
  },
  finalCta: {
    title: "Siap Menghasilkan dari Kontenmu?",
    subtitle: "Gratis selamanya. Upgrade kapan saja. Cairkan kapan saja.",
    button: "Daftar Sekarang — Gratis",
  },
  footer: {
    description: "Platform monetisasi konten untuk kreator Indonesia.",
    productHeading: "Produk",
    pricingLink: "Harga",
    howItWorksLink: "Cara Kerja",
    exploreLink: "Explore Kreator",
    legalHeading: "Legal",
    termsLink: "Syarat & Ketentuan",
    privacyLink: "Kebijakan Privasi",
    contactLink: "Kontak",
    socialHeading: "Ikuti Kami",
    copyright: "© 2026 YourPage. Semua hak dilindungi.",
  },
  auth: {
    loginTitle: "Selamat Datang 👋",
    loginSubtitle: "Masuk ke akun kamu",
    registerTitle: "Buat Akun Baru ✨",
    registerSubtitle: "Daftar gratis dalam 2 menit",
    emailLabel: "Email",
    passwordLabel: "Password",
    confirmPasswordLabel: "Ulangi Password",
    usernameLabel: "Username",
    usernamePlaceholder: "huruf & angka saja",
    roleSelectorLabel: "Saya daftar sebagai",
    roleSupporterLabel: "Supporter",
    roleSupporterDesc: "Beli konten, kirim donasi, chat dengan kreator",
    roleCreatorLabel: "Kreator",
    roleCreatorDesc: "Jual konten, terima donasi, buka page sendiri",
    referralLabel: "Kode Referral",
    referralOptional: "(opsional)",
    referralPlaceholder: "Masukkan kode",
    referralBonus: "🎁 Kamu dan teman yang mengajak akan dapat 10 Credit gratis!",
    forgotPasswordLink: "Lupa password?",
    loginButton: "Masuk",
    registerButton: "Daftar Sekarang",
    orDivider: "atau",
    loginWithQR: "Masuk via QR Code",
    magicLinkButton: "Kirim Magic Link",
    alreadyHaveAccount: "Sudah punya akun?",
    dontHaveAccount: "Belum punya akun?",
    termsAgreement: "Dengan mendaftar, kamu setuju dengan Syarat & Ketentuan dan Kebijakan Privasi.",
    invalidEmail: "Format email tidak valid",
    passwordMismatch: "Konfirmasi password tidak cocok",
    passwordMin: "Minimal 8 karakter",
    registerFailed: "Registrasi gagal",
    hidePassword: "Sembunyikan password",
    showPassword: "Tampilkan password",
    sending: "Mengirim...",
    forgotTitle: "Lupa Password? 🔑",
    forgotSubtitle: "Masukkan email akun kamu, kami kirimkan link reset.",
    forgotSendButton: "Kirim Link Reset",
    forgotSentTitle: "Email Terkirim!",
    forgotSentDesc: "Cek inbox {email} dan klik link reset password. Link berlaku 15 menit.",
    forgotSendFailed: "Gagal mengirim email",
    backToLogin: "← Kembali ke Login",
    resetTitle: "Reset Password",
    resetSubtitle: "Membuat kata sandi baru untuk akun kamu",
    resetNewPassword: "Password Baru",
    resetConfirmPassword: "Konfirmasi Password",
    resetButton: "Reset Password",
    resetSuccessTitle: "Password berhasil direset!",
    resetSuccessDesc: "Silakan login dengan password baru kamu.",
    resetFailed: "Gagal reset password",
    newPasswordPlaceholder: "Minimal 8 karakter",
    invalidToken: "Link tidak valid atau sudah kadaluarsa.",
    verifyTitle: "Memverifikasi...",
    verifyDesc: "Sedang memverifikasi email kamu.",
    verifySuccess: "Email Terverifikasi! ✅",
    verifySuccessDesc: "Akun kamu sudah aktif sepenuhnya.",
    verifyFailed: "Link Tidak Valid",
    verifyFailedDesc: "Link verifikasi sudah expired atau tidak valid.",
    verifying: "Memverifikasi...",
    goToLogin: "Kembali ke Login",
    openDashboard: "Buka Dashboard",
    redirectingDashboard: "Redirect ke dashboard dalam {count} detik...",
    qrConfirmTitle: "Setujui login di perangkat lain?",
    qrConfirmDesc: "Perangkat yang menampilkan kode ini akan masuk sebagai {name}. Lanjutkan hanya jika kamu sendiri yang membuka halaman login itu.",
    qrConfirming: "Menyetujui…",
    qrConfirmSuccess: "Login disetujui",
    qrAddDesc: "Perangkat yang menampilkan kode QR sekarang masuk sebagai {name}.",
    qrConfirmFailed: "Kode QR tidak valid atau sudah kedaluwarsa.",
    qrMissingTitle: "Kode QR tidak lengkap",
    qrMissingDesc: "Scan ulang kode dari halaman login di perangkat yang ingin kamu masuki.",
    qrLoginRequiredTitle: "Masuk dulu di perangkat ini",
    qrLoginRequiredDesc: "Kamu perlu login di HP ini sebelum bisa menyetujui login di perangkat lain.",
    qrDoingDesc: "Membuat konfirmasi...",
    qrCancelButton: "Batal",
    qrConfirmButton: "Setujui",
    loading: "Memuat...",
    suspendedTitle: "Akun Ditangguhkan",
    suspendedDesc: "Jelaskan mengapa akun kamu harus dipulihkan:",
    appealDesc: "Jelaskan mengapa akun kamu harus dipulihkan:",
    appealPlaceholder: "Tulis banding kamu...",
    appealSendButton: "Kirim Banding",
    appealSubmitted: "Banding sudah dikirim. Kami akan meninjau dalam 1-3 hari kerja.",
    appealReviewing: "Sedang meninjau...",
    appealSuccess: "Banding terkirim",
    appealFailed: "Gagal mengirim banding",
    logoutButton: "Keluar",
  },
  creatorPage: {
    notFound: "Kreator tidak ditemukan",
    followersCount: "Followers",
    postsCount: "Posts",
    editProfile: "Edit Profil",
    shareProfile: "Bagikan",
    followButton: "Follow",
    unfollowButton: "Unfollow",
    donateButton: "Donasi",
    chatButton: "Chat",
    topSupporterTitle: "Top Supporter",
    becomeMemberTitle: "Jadi Member",
    memberBadge: "✓ Member",
    perMonth: "Credit/bulan",
    supportCreator: "Dukung",
    donateModalTitle: "Beri Apresiasi untuk",
    donateSuccessTitle: "Donasi Terkirim! 🎉",
    donateSuccessDesc: "Terima kasih atas apresiasi dan dukunganmu untuk karya lokal.",
    donateAgain: "Donasi Lagi",
    customAmountPlaceholder: "Nominal lain (min {min})",
    messagePlaceholder: "Pesan (opsional)",
    sendDonationButton: "Kirim",
    paidByCredits: "Dibayar dengan Credit dari wallet kamu",
    tabPosts: "Post",
    tabProducts: "Katalog",
    tabMembership: "Membership",
    emptyPostsTitle: "Belum ada post",
    emptyPostsDesc: "Kreator ini sedang menyiapkan karya terbaiknya. Follow untuk jadi yang pertama tahu saat post dirilis!",
    emptyProductsTitle: "Belum ada produk",
    emptyProductsDesc: "Belum ada produk digital yang dijual saat ini. Ingin request materi? Sapa kreator lewat tombol Chat.",
  },
  post: {
    lockedTitle: "Konten Spesial Terkunci",
    lockedDesc: "Beli sekali, akses selamanya di Library kamu.",
    unlockButton: "Buka Akses Konten Ini",
    previewBadge: "Preview",
    commentsTitle: "Komentar",
    emptyComments: "Belum ada komentar. Jadilah yang pertama!",
    writeComment: "Tulis komentar...",
    sendComment: "Kirim",
    freeBadge: "Gratis",
    previewHint: "👆 Preview — beli untuk baca selengkapnya",
    paidContent: "Konten Berbayar",
    buyForLogin: "Masuk untuk Membeli",
    registerFree: "Belum punya akun?",
    topupNow: "Top-up Credit Sekarang",
    needCreditsPost: "Kamu butuh {price} untuk membuka konten ini",
    processing: "Memproses...",
    likeCount: "{count} Suka",
    commentCount: "{count} Komentar",
    shareButton: "Bagikan",
    shareAria: "Bagikan post",
    copyLink: "Copy Link",
    linkCopied: "Link disalin!",
    shareWhatsApp: "WhatsApp",
    shareTwitter: "Twitter",
    attachedDocument: "Dokumen terlampir",
    insufficientCredits: "Credit tidak cukup.",
    openPost: "Buka post",
    buyPost: "Beli — {price}",
  },
  product: {
    filesIncluded: "File yang didapat",
    salesCount: "terjual",
    buyButton: "Beli Sekarang",
    downloadButton: "Download File",
    purchasedBadge: "Sudah Dibeli",
    topupRequired: "Credit tidak cukup. Top-up dulu.",
    inactiveBadge: "Tidak Aktif",
    deliveryLink: "Link",
    deliveryFile: "File",
    description: "Deskripsi",
    salesSold: "{count} terjual",
    needCreditsProduct: "Kamu butuh {price} untuk membeli produk ini",
    alreadyPurchased: "Sudah Dibeli",
    fileExpired: "kedaluwarsa",
    noFiles: "Kreator belum mengunggah file untuk produk ini.",
    creatorNoFiles: "Kreator belum mengunggah file untuk produk ini.",
    openLink: "Buka Link",
    buyForLogin: "Masuk untuk Membeli",
    registerFree: "Belum punya akun?",
    topupNow: "Top-up Credit Sekarang",
    processing: "Memproses...",
    insufficientCredits: "Credit tidak cukup.",
    buyProduct: "Beli — {price}",
  },
  profilePage: {
    loading: "Memuat...",
    dashboard: "Dashboard",
    upgradeToCreator: "Upgrade ke Creator",
    redirecting: "Redirecting...",
  },
  wallet: {
    creditBalance: "Saldo Credit",
    topupButton: "Top-up Credit",
    withdrawButton: "Tarik Dana",
    creditRateNote: "1 Credit = Rp 1.000",
    transactionHistory: "Riwayat Transaksi",
    emptyTransactions: "Belum ada transaksi",
    withdrawToBank: "💰 Tarik saldo ke rekening bank",
    topupToStart: "Top-up Credit untuk mulai bertransaksi",
    topupSuccess: "Top-up Berhasil! 🎉",
    topupSuccessDesc: "{credits} Credit sudah masuk ke saldo kamu.",
    paymentFailed: "Pembayaran Gagal",
    paymentSessionExpired: "Sesi pembayaran berakhir. Silakan coba lagi.",
    verifyingPayment: "Memverifikasi pembayaran…",
    verifyingPaymentDesc: "Sebentar ya, kami sedang konfirmasi ke Stripe.",
    goToWallet: "Ke Wallet",
    paymentCancelled: "Pembayaran Dibatalkan",
    noFundsCharged: "Tidak ada dana yang terpotong.",
    yourBalance: "Saldo kamu: {balance} Credit",
    chooseAmount: "Pilih Nominal",
    noPaymentMethod: "⚠ Belum ada metode pembayaran aktif. Hubungi admin.",
    customAmountPlaceholder: "Nominal lain (min 10.000)",
    youWillGet: "Kamu akan mendapat {credits} Credit",
    paymentMethod: "Metode Pembayaran",
    qris: "QRIS",
    qrisDesc: "GoPay · OVO · Dana · ShopeePay · M-Banking — verifikasi 1×24 jam",
    card: "Kartu Kredit/Debit",
    stripeDesc: "Via Stripe — credit masuk otomatis ⚡",
    payWithCard: "Bayar dengan Kartu →",
    continueAction: "Lanjut →",
    transferAndUploadProof: "Transfer & Upload Bukti",
    transferExactAmount: "Transfer tepat sebesar",
    uniqueCode: "Kode unik:",
    uniqueCodeNote: "Nominal harus tepat termasuk kode unik agar transfer kamu bisa dikenali otomatis",
    scanQris: "Scan QRIS di bawah:",
    qrisChannels: "GoPay · OVO · Dana · ShopeePay · QRIS · M-Banking",
    qrisNotConfigured: "QRIS belum diatur admin",
    senderName: "Nama Pengirim",
    senderNamePlaceholder: "Nama di rekening / e-wallet",
    transferProof: "Bukti Transfer",
    maxFileSize: "Maksimal 10MB",
    tapToUpload: "Tap untuk upload bukti",
    sending: "Mengirim...",
    sendProof: "Kirim Bukti Transfer",
    proofReceived: "Bukti Transfer Diterima",
    pendingVerification: "Menunggu verifikasi admin (1×24 jam). Credit akan ditambahkan setelah disetujui.",
    notificationNote: "Kamu akan mendapat notifikasi setelah admin memverifikasi.",
    topupAgain: "Top-up Lagi",
  },
  supporterHub: {
    feedTitle: "Feed",
    explore: "Explore",
    findCreators: "Temukan kreator",
    donations: "Donasi",
    history: "Riwayat",
    exploreCreators: "Explore Kreator",
    emptyFeedTitle: "Belum ada konten",
    emptyFeedDesc: "Follow kreator untuk melihat konten mereka.",
    purchasedPosts: "Post yang Dibeli",
    emptyPurchasedPosts: "Belum ada post yang dibeli",
    emptyPurchasedPostsDesc: "Beli konten dari kreator favoritmu",
    purchasedProducts: "Produk yang Dibeli",
    emptyPurchasedProducts: "Belum ada produk yang dibeli",
    emptyPurchasedProductsDesc: "Beli produk dari kreator favoritmu",
    donationsSent: "Donasi Terkirim",
    totalDonations: "Total Donasi",
    creatorsSupported: "Kreator Didukung",
    emptyDonationsSent: "Belum pernah mengirim donasi",
    supportCreatorsCta: "Dukung kreator favoritmu →",
    net: "Net:",
    totalSpent: "Total Pengeluaran",
    transactions: "Transaksi",
    buyPost: "Beli Post",
    buyProduct: "Beli Produk",
    donation: "Donasi",
    topupCredit: "Top-up Credit",
    type: "Tipe",
    amount: "Jumlah",
    date: "Tanggal",
    invoice: "Invoice",
    print: "Print",
    txId: "ID Transaksi",
    creditAmount: "{credits} Credit",
    digitalReceipt: "Bukti transaksi digital — YourPage",
    total: "Total:",
    income: "Masuk",
    outgoing: "Keluar",
    settings: "Settings",
    profile: "Profil",
    blockedUsers: "User yang Diblokir",
    blockedUsersDesc: "User yang kamu blokir tidak bisa follow, chat, atau berinteraksi denganmu.",
    emptyBlocked: "Kamu belum memblokir siapapun.",
    blockedOn: "Diblokir {date}",
    unblockButton: "Buka Blokir",
    unblockSuccess: "User berhasil di-unblock",
    unblockError: "Gagal unblock user",
    emptyDonations: "Belum ada donasi.",
  },
  dashboard: {
    greetingMorning: "Selamat pagi",
    greetingAfternoon: "Selamat siang",
    greetingEvening: "Selamat malam",
    totalEarnings: "Total Pendapatan",
    setupTitle: "Setup Halaman",
    newPostButton: "Post Baru",
    myPageButton: "Halaman Saya",
  },
  dashboardCore: {
    credit: "Credit",
    viewDetails: "Lihat detail",
    followers: "Followers",
    walletBalance: "Wallet",
    view: "Lihat →",
    sales7Days: "Penjualan 7 Hari",
    total: "Total:",
    all: "Semua",
    noSalesData: "Belum ada data penjualan",
    createPost: "Buat Post",
    createProduct: "Buat Produk",
    withdrawBalance: "Tarik Saldo",
    upgrade: "Upgrade",
    checkUploadAvatar: "Upload avatar",
    checkWriteBio: "Tulis bio",
    checkFirstPost: "Buat post pertama",
    checkVerifyKyc: "Verifikasi KYC",
    analyticsAdvanced: "Analytics Advanced",
    analyticsProOnly: "Tersedia untuk tier Pro dan Business.",
    upgradeNow: "Upgrade Sekarang",
    analytics: "Analytics",
    exportCsv: "Export CSV",
    exportFailed: "Gagal export.",
    loadFailed: "Gagal memuat data.",
    feeTier: "Fee Tier",
    upgradeLowerFee: "Upgrade untuk fee lebih rendah →",
    statPosts: "Posts",
    statProducts: "Produk",
    statFollowers: "Followers",
    statSales: "Penjualan",
    statRevenue: "Revenue",
    statDonations: "Donasi",
    upgradeBusinessExport: "Upgrade ke Business untuk export CSV",
    upgradeToBusiness: "Upgrade ke Business",
    viewWallet: "Lihat Wallet",
    profileSaved: "Profil berhasil disimpan!",
    saveFailed: "Gagal menyimpan",
    viewPublicPage: "Lihat Halaman Publik",
    bannerAvatarTitle: "🖼️ Banner & Avatar",
    uploadBanner: "Upload banner (1500×400px)",
    changeBanner: "Ganti Banner",
    deleteBanner: "Hapus banner",
    deleteBannerTitle: "Hapus Banner?",
    deleteBannerDesc: "Banner akan dihapus setelah kamu klik Simpan.",
    changeAvatar: "Ganti Avatar",
    infoTitle: "📝 Informasi",
    bioLabel: "Bio",
    bioPlaceholder: "Contoh: Kreator konten edukasi keuangan 💰 | Tips investasi & budgeting untuk anak muda Indonesia",
    charCount: "{count}/500 karakter",
    categoryLabel: "Kategori",
    categoryHint: "Ditampilkan di halaman Explore agar supporter mudah menemukan kamu",
    usernameHint: "Username digunakan sebagai link halaman kamu: urpage.online/c/{username}",
    socialTitle: "🔗 Social Media",
    channelUrlPlaceholder: "Channel URL",
    customizeTitle: "🎨 Kustomisasi",
    pageAccentColor: "Warna aksen halaman",
    saving: "Menyimpan...",
    saveProfile: "Simpan Profil",
    donationsReceived: "Donasi Diterima",
    totalDonations: "Total Donasi",
    netReceived: "Net Diterima",
    donors: "Donatur",
    anonymous: "Anonim",
    net: "Net:",
    noDonations: "Belum ada donasi",
    noDonationsDesc: "Bagikan halaman kamu untuk mulai menerima donasi",
  },
  chat: {
    title: "Chat",
    newChatTitle: "Chat Baru",
    newChatSubtitle: "Kirim pesan pertama",
    pricePerMessage: "Setiap pesan dikenakan {price} Credit",
    inputPlaceholder: "Tulis pesan...",
    sendButton: "Kirim",
    sendFailed: "Gagal kirim pesan",
    conversationsCount: "{count} percakapan",
    emptyConversationsTitle: "Belum ada percakapan",
    emptyConversationsDesc: "Kunjungi halaman kreator dan mulai chat",
    selectConversationTitle: "Pilih percakapan",
    selectConversationDesc: "Pilih chat dari daftar di samping",
    startConversationPrompt: "Mulai percakapan...",
    paidBadge: "Paid",
    sendMessageAria: "Kirim pesan",
    loadFailed: "Chat gagal dimuat",
  },
  feedPage: {
    title: "Feed",
    emptyTitle: "Feed kosong",
    emptyDesc: "Follow kreator untuk lihat post mereka di sini",
    findCreators: "Temukan Kreator",
  },
  notifications: {
    title: "Notifikasi",
    markAllRead: "Tandai dibaca",
    today: "Hari ini",
    yesterday: "Kemarin",
    allReadTitle: "Semua sudah dibaca",
    allReadDesc: "Notifikasi baru akan muncul di sini",
  },
  upgrade: {
    title: "Jadi Creator",
    subtitle: "Mulai monetisasi kontenmu di YourPage",
    displayNameLabel: "Display Name",
    displayNamePlaceholder: "Nama tampilan",
    pageSlugLabel: "Page Slug",
    slugPlaceholder: "username",
    pageHint: "Halaman kamu: yourpage.id/c/{slug}",
    upgradeFailed: "Gagal upgrade",
    processing: "Memproses...",
    upgradeButton: "Upgrade ke Creator",
  },
  // --- Extended pricing keys (pricing page) ---
  pricingPage: {
    transparentPricing: "Harga Transparan",
    subtitle: "Mulai gratis, upgrade kapan saja. Makin tinggi tier, makin rendah fee-nya.",
    popular: "Populer",
    freePrice: "Gratis",
    perMonth: "per bulan",
    takeHome: "Kamu terima {percent}% dari tiap transaksi",
    currentPlan: "Paket Saat Ini",
    upgrade: "Upgrade",
    startNow: "Mulai Sekarang",
    featureComparison: "Perbandingan Fitur",
    feature: "Fitur",
    free: "Free",
    pro: "Pro",
    business: "Business",
    yes: "Ya",
    no: "Tidak",
    postBerbayar: "Post berbayar",
    produkDigital: "Produk digital",
    storage: "Storage",
    platformFee: "Platform fee",
    kamuTerima: "Kamu terima (take-home)",
    analytics: "Analytics",
    customPage: "Custom page",
    scheduledPosts: "Scheduled posts",
    prioritySupport: "Priority support",
    badgeKhusus: "Badge khusus",
  },
  explore: {
    searchPlaceholder: "Cari kreator...",
    clearSearch: "Hapus pencarian",
    all: "Semua",
    trending: "Trending",
    allCreators: "Semua Kreator",
    verified: "Terverifikasi",
    notFound: "Tidak ditemukan",
    notFoundDesc: "Coba kata kunci lain untuk \u201c{query}\u201d",
    emptyTitle: "Belum ada kreator",
    emptyDesc: "Kreator akan muncul di sini",
    categories: {
      Gaming: "Gaming",
      Musik: "Musik",
      Edukasi: "Edukasi",
      Podcast: "Podcast",
      Seni: "Seni",
      Teknologi: "Teknologi",
      Lifestyle: "Lifestyle",
      Lainnya: "Lainnya",
    },
  },
  contact: {
    title: "Hubungi Kami",
    subtitle: "Ada pertanyaan atau butuh bantuan?",
    emailLabel: "Email",
    whatsappLabel: "WhatsApp",
  },
  legal: {
    termsTitle: "Syarat & Ketentuan",
    privacyTitle: "Kebijakan Privasi",
    lastUpdated: "Terakhir diperbarui: April 2026",
    terms: {
      section1Title: "1. Tentang YourPage",
      section1Content: "YourPage adalah platform monetisasi konten untuk kreator Indonesia. Dengan menggunakan layanan ini, Anda menyetujui syarat dan ketentuan berikut.",
      section2Title: "2. Akun",
      section2Item1: "Anda harus berusia minimal 17 tahun untuk mendaftar.",
      section2Item2: "Informasi yang diberikan harus akurat dan terkini.",
      section2Item3: "Anda bertanggung jawab atas keamanan akun Anda.",
      section2Item4: "Satu orang hanya boleh memiliki satu akun.",
      section3Title: "3. Konten",
      section3Item1: "Kreator bertanggung jawab penuh atas konten yang dipublikasikan.",
      section3Item2: "Dilarang mempublikasikan konten NSFW, kekerasan, ujaran kebencian, atau melanggar hukum.",
      section3Item3: "YourPage berhak menghapus konten dan menangguhkan akun yang melanggar.",
      section4Title: "4. Pembayaran & Fee",
      section4Item1: "Platform fee sebesar 10% dikenakan pada setiap transaksi (post, produk, donasi).",
      section4Item2: "Harga yang ditetapkan kreator sudah termasuk PPN (inclusive).",
      section4Item3: "Credit yang dibeli tidak dapat dicairkan kembali.",
      section4Item4: "Minimum penarikan adalah Rp 100.000.",
      section4Item5: "KYC (verifikasi identitas) wajib untuk penarikan pertama.",
      section5Title: "5. Refund & Sengketa",
      section5Item1: "Platform tidak menyediakan refund otomatis.",
      section5Item2: "Sengketa ditangani oleh admin secara manual.",
      section5Item3: "Dalam kasus chargeback, platform berhak memotong saldo kreator terkait.",
      section6Title: "6. Penangguhan",
      section6Content: "YourPage berhak menangguhkan atau menghapus akun yang melanggar ketentuan tanpa pemberitahuan sebelumnya.",
      section7Title: "7. Perubahan Ketentuan",
      section7Content: "YourPage dapat mengubah syarat dan ketentuan ini sewaktu-waktu. Perubahan akan diumumkan melalui platform.",
    },
    privacy: {
      section1Title: "1. Data yang Kami Kumpulkan",
      section1Item1: "Akun: Email, username, password (terenkripsi).",
      section1Item2: "Profil: Nama tampilan, bio, avatar (opsional).",
      section1Item3: "KYC: Nama lengkap, nomor KTP, foto KTP (hanya untuk verifikasi penarikan).",
      section1Item4: "Transaksi: Riwayat pembelian, donasi, dan penarikan.",
      section2Title: "2. Penggunaan Data",
      section2Item1: "Menyediakan dan meningkatkan layanan platform.",
      section2Item2: "Memproses transaksi dan pembayaran.",
      section2Item3: "Verifikasi identitas untuk penarikan dana.",
      section2Item4: "Mengirim notifikasi terkait akun dan transaksi.",
      section3Title: "3. Perlindungan Data",
      section3Item1: "Email tidak pernah ditampilkan di halaman publik.",
      section3Item2: "Password disimpan dalam bentuk hash (bcrypt).",
      section3Item3: "Data KTP hanya dapat diakses oleh admin untuk verifikasi.",
      section3Item4: "JWT hanya berisi user ID dan role \u2014 tidak ada data pribadi.",
      section3Item5: "Semua koneksi menggunakan HTTPS (production).",
      section4Title: "4. Penyimpanan",
      section4Item1: "Data disimpan di server yang berlokasi di Indonesia.",
      section4Item2: "File media disimpan di object storage terenkripsi.",
      section4Item3: "Data tidak dijual atau dibagikan ke pihak ketiga.",
      section5Title: "5. Hak Pengguna",
      section5Item1: "Anda dapat mengubah atau menghapus data profil kapan saja.",
      section5Item2: "Untuk penghapusan akun, hubungi admin.",
      section6Title: "6. Kontak",
      section6Item1: "Pertanyaan tentang privasi dapat dikirim ke admin melalui platform.",
    },
  },
  statusPage: {
    title: "YourPage Status",
    allNormal: "Semua Sistem Normal",
    disruption: "Ada Gangguan",
    website: "Website",
    api: "API",
    database: "Database",
    autoRefresh: "Auto-refresh setiap 30 detik",
  },
  offlinePage: {
    title: "Kamu Sedang Offline",
    description: "Pastikan koneksi internet dan coba lagi.",
    retry: "Coba Lagi",
  },
  overlayAlerts: {
    missingIdTitle: "Overlay URL tidak lengkap",
    missingIdDesc: "Tambahkan ?id=<creator-id> pada URL. Salin URL lengkapnya dari Dashboard → Overlay.",
    ttsDonate: "{name} berdonasi {amount} credit",
    defaultGoalTitle: "Target Donasi",
    goalProgress: "{current} dari {target}",
    anonymous: "Anonim",
  },
  adminOverview: {
    panelLabel: "Admin Panel",
    dashboardLabel: "Dashboard",
    allProcessed: "Semua sudah diproses! 🎉",
    topupLabel: "Top-up {amount} → {credits} Credit",
    viewProof: "Lihat bukti",
    approve: "Setujui",
    reject: "Tolak",
    rejectTopupTitle: "Tolak Top-up?",
    rejectTopupMessage: "Yakin ingin menolak top-up ini?",
    withdrawalLabel: "Penarikan {amount}",
    rejectWithdrawalTitle: "Tolak Penarikan?",
    rejectWithdrawalMessage: "Yakin ingin menolak penarikan ini?",
    kycLabel: "KYC: {name}",
    kycApproved: "KYC disetujui",
    rejectKycTitle: "Tolak KYC?",
    rejectKycMessage: "Yakin ingin menolak KYC {name}?",
    rejectConfirmLabel: "Tolak",
    revenueSection: "Pendapatan",
    gmv: "GMV",
    revenueFee: "Pendapatan (Fee)",
    donations: "Donasi",
    withdrawn: "Ditarik",
    platformSection: "Platform",
    users: "Pengguna",
    creators: "Kreator",
    posts: "Post",
    products: "Produk",
    reports: "Laporan",
    reportsPending: "{count} menunggu",
    linkUsers: "Pengguna",
    linkPayments: "Pembayaran",
    linkReports: "Laporan",
    linkProfit: "Profit",
    breadcrumbAdmin: "Admin",
    breadcrumbUsers: "Pengguna",
    userListTitle: "Pengguna",
    addUserFinance: "Pengguna Finance",
    financeUserTitle: "Tambah Pengguna Finance",
    createFinanceUser: "Buat Pengguna Finance",
    searchPlaceholder: "Cari username, nama...",
    noUsers: "Tidak ada pengguna.",
    userDetailTitle: "Detail Pengguna",
    userId: "ID:",
    joined: "Bergabung:",
    bio: "Bio:",
    viewPage: "Lihat Halaman",
    banUser: "Ban Pengguna",
    unbanUser: "Lift Ban",
    bannedBadge: "Diblokir",
    banConfirmTitle: "Ban Pengguna?",
    banConfirmMessage: "Yakin ingin ban {name}?",
    promoCreatorTitle: "Promo Kreator",
    promoFeePercent: "Fee Promo %",
    promoFeePlaceholder: "Kosong = pakai tier",
    promoDurationDays: "Durasi (hari)",
    featuredHomepage: "Featured di homepage",
    adminNoteOptional: "Catatan admin (opsional)",
    savePromo: "Simpan Promo",
    resetPromo: "Reset Promo",
    paymentHistoryTitle: "Riwayat Pembayaran ({count})",
    donationHistoryTitle: "Riwayat Donasi ({count})",
    noPayments: "Tidak ada pembayaran.",
    noDonations: "Tidak ada donasi.",
    adminProfileTitle: "Profil Admin",
    profileCardTitle: "Profil",
    settingsTitle: "Pengaturan Platform",
    configuration: "Konfigurasi",
    platformFeePercent: "Platform Fee (%)",
    minWithdrawalIdr: "Min Withdrawal (IDR)",
    creditRateIdr: "Credit Rate (IDR per credit)",
    saving: "Menyimpan...",
    save: "Simpan",
    qrisPlatform: "QRIS Platform",
    qrisDescription: "Gambar QRIS yang ditampilkan ke pengguna saat top-up manual.",
    noQris: "Belum ada QRIS",
    uploadNewQris: "Upload QRIS Baru",
    uploading: "Mengunggah...",
    uploadFailed: "Gagal upload",
    paymentMethods: "Metode Pembayaran Top-up",
    qrisManual: "QRIS Manual",
    qrisManualDesc: "Pengguna transfer via QRIS, upload bukti, admin verifikasi manual.",
    enableQris: "Aktifkan QRIS",
    qrisUploadWarning: "⚠ Upload gambar QRIS dulu agar pengguna bisa scan.",
    stripeCard: "Stripe (Kartu)",
    stripeDesc: "Pembayaran kartu otomatis via Stripe Checkout. Credit masuk instan.",
    enableStripe: "Aktifkan Stripe",
    stripeConfiguration: "Konfigurasi Stripe",
    publishableKey: "Publishable Key",
    secretKey: "Secret Key",
    webhookSecret: "Webhook Signing Secret",
    webhookEndpoint: "Endpoint webhook",
    keySecurityNote: "Key tersimpan aman — API hanya menampilkan 4 karakter terakhir. Isi ulang hanya jika ingin mengganti.",
    showSecret: "Tampilkan",
    hideSecret: "Sembunyikan",
    savePaymentMethods: "Simpan Metode Pembayaran",
    settingsSaved: "Pengaturan tersimpan!",
    paymentMethodsSaved: "Metode pembayaran tersimpan!",
    settingsSaveFailed: "Gagal menyimpan",
  },
  monetization: {
    donationSettingsTitle: "Pengaturan Donasi",
    donationGoalTitle: "Target Donasi",
    donationGoalDesc: "Tampilkan target donasi di halaman kamu untuk memotivasi supporter.",
    goalTitleLabel: "Judul Target",
    goalTitlePlaceholder: "Contoh: Beli kamera baru untuk konten lebih bagus 📸",
    goalAmountLabel: "Target Nominal",
    goalAmountPlaceholder: "Target (Credit)",
    creditUnit: "Credit",
    goalCollected: "{amount} terkumpul",
    goalTargetLabel: "target",
    goalPercentReached: "{percent}% tercapai",
    preset500Credit: "500 Credit",
    preset1kCredit: "1K Credit",
    preset5kCredit: "5K Credit",
    welcomeMessageTitle: "Pesan Penyambutan",
    welcomeMessageDesc: "Pesan otomatis yang tampil setelah seseorang berdonasi atau membeli produk kamu.",
    welcomeMessagePlaceholder: "Contoh: Terima kasih banyak atas dukungannya! 🙏 Kamu yang terbaik. Cek konten eksklusif saya di tab Posts ya!",
    saving: "Menyimpan...",
    saveSettings: "Simpan Pengaturan",
    settingsSaved: "Pengaturan disimpan!",
    saveFailed: "Gagal",
    chatSettingsTitle: "Pengaturan Chat",
    chatPriceTitle: "Harga Chat",
    chatPriceLabel: "Harga per pesan (Credit)",
    chatPricePlaceholder: "0 = gratis",
    freeChatNote: "Chat gratis — semua supporter bisa kirim pesan tanpa biaya.",
    simulationTitle: "Simulasi per pesan:",
    simulationSenderPays: "Pengirim bayar",
    simulationYouGet: "Kamu dapat",
    simulationFee: "Fee ({percent}%)",
    preset5Credit: "5 Credit",
    preset10Credit: "10 Credit",
    preset25Credit: "25 Credit",
    presetFree: "Gratis",
    whoCanChatTitle: "Siapa yang Boleh Chat",
    whoCanChatDesc: "Atur siapa saja yang bisa memulai percakapan dengan kamu.",
    chatOptionAllLabel: "👥 Semua",
    chatOptionAllDesc: "Supporter & creator",
    chatOptionSupporterLabel: "🙋 Supporter Saja",
    chatOptionSupporterDesc: "Hanya supporter",
    chatOptionCreatorLabel: "🎨 Creator Saja",
    chatOptionCreatorDesc: "Hanya sesama creator",
    chatOptionNoneLabel: "🔕 Tidak Ada",
    chatOptionNoneDesc: "Chat dinonaktifkan",
    chatDisabledWarning: "⚠️ Tidak ada yang bisa memulai chat baru denganmu.",
    autoReplyTitle: "🤖 Auto-Reply",
    businessBadgeLabel: "Business",
    autoReplyDesc: "Pesan otomatis yang dikirim saat supporter mengirim chat pertama.",
    autoReplyPlaceholder: "Contoh: Terima kasih sudah menghubungi! Saya akan balas segera 😊",
    autoReplyActive: "✅ Auto-reply aktif",
    upgradeToBusiness: "Upgrade ke Business untuk mengaktifkan auto-reply.",
    upgradeButton: "Upgrade",
    chatLimitsTitle: "📊 Limit Chat",
    dailyReplies: "Balasan per hari",
    dailyRepliesUnlimited: "Unlimited",
    dailyRepliesLimited: "10 / hari",
    senderRequirement: "Syarat pengirim",
    mustFollow: "Harus follow kamu",
    yourFeeTier: "Fee tier kamu",
    chatSettingsSaved: "Pengaturan chat disimpan!",
    chatSaveFailed: "Gagal menyimpan",
    membershipTitle: "Fan Membership",
    activeMembers: "Member Aktif",
    tierCountLabel: "Tier",
    membershipTiersLabel: "Tier Membership",
    creditPerMonth: "Credit/bulan",
    deleteTierTitle: "Hapus Tier?",
    deleteTierMessage: "Yakin ingin hapus tier \"{name}\"?",
    deleteConfirmLabel: "Hapus",
    noTiersYet: "Belum ada tier. Buat di samping →",
    createNewTier: "Buat Tier Baru",
    tierNameLabel: "Nama Tier",
    tierNamePlaceholder: "Bronze, Silver, Gold",
    tierPriceLabel: "Harga (Credit/bulan)",
    tierPricePlaceholder: "10",
    tierDescriptionLabel: "Deskripsi",
    tierDescriptionPlaceholder: "Deskripsi singkat",
    tierPerksPlaceholder: "Perks (misal: Akses post eksklusif, Chat prioritas)",
    creating: "Membuat...",
    createTierButton: "Buat Tier",
    tierCreated: "Tier dibuat!",
    tierDeleted: "Tier dihapus",
    deleteTierFailed: "Gagal menghapus tier",
    salesTitle: "Penjualan",
    netRevenue: "Net Revenue",
    postLabel: "Post",
    productLabel: "Produk",
    donationLabel: "Donasi",
    colType: "Tipe",
    colBuyer: "Pembeli",
    colGross: "Gross",
    colNet: "Net",
    colDate: "Tanggal",
    noSalesTitle: "Belum ada penjualan",
    noSalesDesc: "Buat konten berbayar untuk mulai menghasilkan",
    breadcrumbDashboard: "Dashboard",
    breadcrumbWithdrawals: "Penarikan",
    withdrawalsTitle: "Penarikan Dana",
    withdrawButtonLabel: "💰 Tarik Dana",
    creditBalanceLabel: "Saldo Credit",
    totalEarningsLabel: "Total Pendapatan",
    withdrawalFormTitle: "Form Penarikan",
    amountLabel: "Nominal Credit (min {min})",
    amountPlaceholder: "100",
    amountEquivalent: "= Rp {amount}",
    bankNamePlaceholder: "Nama Bank (BCA, BNI, Mandiri, dll)",
    accountNumberPlaceholder: "Nomor Rekening (10-16 digit)",
    confirmAccountPlaceholder: "Konfirmasi Nomor Rekening",
    accountNamePlaceholder: "Nama Pemilik Rekening (sesuai KTP)",
    accountMismatch: "Nomor rekening tidak cocok",
    processing: "Memproses...",
    submitRequest: "Kirim Request",
    validationDigitsError: "Nomor rekening harus 10-16 digit angka",
    minimumWithdrawal: "Minimum penarikan {min} Credit",
    insufficientBalance: "Saldo tidak cukup",
    kycRequired: "KYC harus diverifikasi terlebih dahulu",
    noWithdrawals: "Belum ada penarikan",
    adminNote: "Admin: {note}",
  },
  welcomePage: {
    title: "Selamat datang! \uD83C\uDF89",
    accountCreated: "Akun kamu berhasil dibuat. Ini yang bisa kamu lakukan:",
    creator: {
      createPost: "Buat Post Pertama",
      createPostDesc: "Tulis konten gratis atau berbayar untuk fans kamu.",
      uploadProduct: "Upload Produk Digital",
      uploadProductDesc: "Jual e-book, preset, template, dan lainnya.",
      receiveDonation: "Terima Donasi",
      receiveDonationDesc: "Fans bisa kirim donasi langsung ke halaman kamu.",
    },
    supporter: {
      findCreators: "Temukan Kreator",
      findCreatorsDesc: "Cari dan follow kreator favoritmu.",
      topupCredit: "Top-up Credit",
      topupCreditDesc: "Isi saldo untuk beli konten dan kirim donasi.",
      buyContent: "Beli Konten",
      buyContentDesc: "Akses konten eksklusif dari kreator.",
    },
    openDashboard: "Buka Dashboard",
  },
  contentMgr: {
    // Posts
    postsTitle: "Posts",
    postsPublishedCount: "{count} published",
    postsDraftCount: "{count} draft",
    createPost: "Buat Post",
    close: "Tutup",
    postTitlePlaceholder: "Judul post",
    postContentPlaceholder: "Tulis konten...",
    uploadMedia: "Upload Media",
    accessLabel: "Akses",
    free: "Gratis",
    paid: "Berbayar",
    members: "Members",
    priceCredit: "Harga (Credit)",
    pricePlaceholder: "5",
    previewText: "Preview teks",
    teaserPlaceholder: "Teaser singkat...",
    tierMinimum: "Tier minimum",
    allMembers: "Semua Member",
    creditPerMonth: "{count} Credit/bulan",
    noMembershipTier: "⚠️ Belum punya membership tier.",
    createTierFirst: "Buat dulu",
    scheduleOptional: "Jadwalkan (opsional)",
    saving: "Menyimpan...",
    schedule: "📅 Jadwalkan",
    publish: "🚀 Publish",
    draftHeader: "📝 Draft ({count})",
    emptyPostsTitle: "Belum ada post",
    emptyPostsDesc: "Buat post pertamamu!",
    deletePostTitle: "Hapus Post?",
    deletePostMessage: "Post yang dihapus tidak bisa dikembalikan.",
    postCreated: "Post berhasil dipublikasikan!",
    postCreatedFailed: "Gagal membuat post",
    postDeleted: "Post dihapus",
    // Post editor
    back: "Kembali",
    editPost: "Edit Post",
    postTitleLabel: "Judul",
    excerptOptional: "Excerpt (opsional)",
    contentLabel: "Konten...",
    membersOnly: "Members Only",
    selectTierMinimum: "Pilih tier minimum (kosong = semua member)",
    publishedStatus: "✓ Published",
    draftStatus: "Draft",
    save: "Simpan",
    postSaved: "Post tersimpan!",
    saveFailed: "Gagal menyimpan",
    mediaCount: "Media ({count})",
    upload: "Upload",
    noMedia: "Belum ada media.",
    publishedBadge: "Published",
    draftBadge: "Draft",
    // Products
    productsTitle: "Katalog Produk",
    productsCount: "{count} produk",
    productsSoldCount: "{count} terjual",
    createProduct: "Buat Produk",
    productName: "Nama",
    productNamePlaceholder: "Nama produk",
    slug: "Slug",
    slugPlaceholder: "url-friendly",
    descriptionPlaceholder: "Deskripsi produk...",
    typeLabel: "Tipe",
    ebook: "📖 E-book",
    preset: "🎨 Preset",
    template: "📄 Template",
    other: "📦 Lainnya",
    deliveryLabel: "Pengiriman",
    fileDelivery: "📁 File Digital",
    linkDelivery: "🔗 Link / Key",
    deliveryUrlPlaceholder: "URL kursus, license key, invite link",
    thumbnail: "Thumbnail",
    productFiles: "File Produk",
    saveProduct: "Simpan Produk",
    deleteProductTitle: "Hapus Produk?",
    deleteProductMessage: "Produk yang dihapus tidak bisa dikembalikan.",
    productCreated: "Produk berhasil dibuat!",
    productCreatedFailed: "Gagal membuat produk",
    emptyProductsTitle: "Belum ada produk",
    emptyProductsDesc: "Buat produk digital pertamamu!",
    // Product editor
    editProduct: "Edit Produk",
    activeStatus: "✓ Aktif",
    inactiveStatus: "Nonaktif",
    deliveryTypeLabel: "Tipe Pengiriman",
    urlSerialKey: "URL / Serial Key",
    urlSerialKeyPlaceholder: "https://... atau serial key",
    productSaved: "Produk tersimpan!",
    productSaveFailed: "Gagal menyimpan produk",
    saved: "Tersimpan!",
    assetFilesCount: "File Produk ({count})",
    uploadFile: "Upload File",
    noAssets: "Belum ada file.",
    noAssetsDesc: "Upload file yang akan diterima pembeli.",
  },
  adminModeration: {
    // Common
    approve: "Setujui",
    reject: "Tolak",
    delete: "Hapus",
    ban: "Ban",
    view: "Lihat",
    close: "Tutup",
    // Status badges
    statusPending: "Menunggu",
    statusApproved: "Disetujui",
    statusRejected: "Ditolak",
    statusResolved: "Resolved",
    statusDismissed: "Dismissed",
    statusPaid: "Dibayar",
    statusFailed: "Gagal",
    statusActive: "Aktif",
    statusInactive: "Nonaktif",
    // Filter labels
    filterPending: "Menunggu",
    filterApproved: "Disetujui",
    filterRejected: "Ditolak",
    filterPaid: "Dibayar",
    filterFailed: "Gagal",
    filterResolved: "Resolved",
    filterDismissed: "Dismissed",
    // Sort labels
    sortTitle: "Judul",
    sortViews: "Views",
    sortLikes: "Likes",
    sortComments: "Komentar",
    sortDate: "Tanggal",
    sortName: "Nama",
    sortPrice: "Harga",
    sortSales: "Penjualan",
    sortType: "Tipe",
    sortStatus: "Status",
    sortAmount: "Jumlah",
    sortDonor: "Donor",
    sortReason: "Alasan",
    // Search placeholders
    searchPosts: "Cari judul, creator...",
    searchProducts: "Cari nama produk, tipe...",
    searchDonations: "Cari donor, creator...",
    searchKyc: "Cari nama, user ID...",
    searchReports: "Cari reason, target...",
    // Page titles
    postsTitle: "Posts",
    productsTitle: "Products",
    donationsTitle: "Donasi",
    kycTitle: "Verifikasi KYC",
    reportsTitle: "Laporan Konten",
    promoTitle: "Promo & Kerjasama Creator",
    announcementsTitle: "Pengumuman Platform",
    // Empty states
    emptyPosts: "Tidak ada post.",
    emptyProducts: "Tidak ada product.",
    emptyDonations: "Tidak ada donasi.",
    emptyKyc: "Tidak ada KYC.",
    emptyReports: "Tidak ada report.",
    // Posts page
    postDeleteTitle: "Hapus Post?",
    postDeleteMessage: 'Yakin ingin hapus "{name}"?',
    // Products page
    productSold: "terjual",
    productInactive: "Nonaktif",
    productDeleteTitle: "Hapus Produk?",
    productDeleteMessage: 'Yakin ingin hapus "{name}"?',
    // Donations page
    donationFrom: "Dari:",
    donationTo: "Ke:",
    donationNet: "Net:",
    donationPayment: "Payment:",
    donationDate: "Tanggal:",
    donationAnonymous: "Anonim",
    // KYC page
    kycUser: "User:",
    kycSubmitted: "Submitted:",
    kycReviewed: "Reviewed:",
    kycDocAlt: "Dokumen identitas {name}",
    kycDocClickHint: "Klik untuk memperbesar · tautan kedaluwarsa 15 menit",
    kycDocUnavailable: "Dokumen tidak tersedia. Minta user mengunggah ulang sebelum menyetujui.",
    kycNoteLabel: "Note:",
    kycNotePlaceholder: "Catatan (opsional)",
    kycRejectTitle: "Tolak KYC?",
    kycRejectMessage: "Yakin ingin menolak KYC {name}?",
    // Reports page
    reportTarget: "Target:",
    reportReporter: "Reporter:",
    reportDate: "Tanggal:",
    reportNotePlaceholder: "Catatan admin (opsional)",
    reportResolve: "Resolve",
    reportDismiss: "Dismiss",
    reportBanTitle: "Ban User?",
    reportBanMessage: "Yakin ingin ban user ini?",
    reportBanUser: "Ban User",
    reportDeleteTitle: "Hapus {type}?",
    reportDeleteMessage: "Yakin ingin menghapus konten ini?",
    // Promo page
    promoTotalCreator: "Total Creator",
    promoFeatured: "Featured",
    promoTierAvailable: "Tier Tersedia",
    promoVerified: "Verified",
    promoFeaturedCreators: "Featured Creators",
    promoFollowers: "followers",
    promoEditPromo: "Edit Promo",
    promoEmptyFeatured: "Belum ada featured creator. Set di halaman detail user.",
    promoAllCreators: "Semua Creator",
    promoSetPromo: "Set Promo",
    promoTierPricing: "Tier Pricing",
    promoFree: "Gratis",
    promoPerMonth: "/bulan",
    // Announcements page
    announcementsCreateTitle: "Buat Pengumuman Baru",
    announcementsTitlePlaceholder: "Judul pengumuman",
    announcementsBodyPlaceholder: "Isi pengumuman...",
    announcementsAllUsers: "Semua User",
    announcementsOnlyCreator: "Hanya Creator",
    announcementsOnlySupporter: "Hanya Supporter",
    announcementsExpiryPlaceholder: "Kedaluwarsa (opsional)",
    announcementsPublish: "Publish",
    announcementsEmpty: "Belum ada pengumuman.",
    announcementsActive: "Aktif",
    announcementsInactive: "Non-aktif",
    announcementsExpiresLabel: "Kadaluwarsa:",
    announcementsDeleted: "Pengumuman dihapus",
    announcementsDeleteFailed: "Gagal menghapus",
    announcementsValidation: "Title dan isi wajib diisi",
    announcementsCreated: "Pengumuman dibuat!",
    announcementsCreateFailed: "Gagal membuat pengumuman",
  },
  accountMgr: {
    // subscription
    subscriptionTitle: "Subscription",
    subscriptionActiveUntil: "Tier aktif sampai: {date}",
    subscriptionActive: "Aktif",
    subscriptionFree: "Gratis",
    subscriptionCreditPerMonth: "Credit/bulan",
    subscriptionFeeLabel: "Fee",
    subscriptionStorageLabel: "Storage",
    subscriptionCurrentPlan: "Paket Saat Ini",
    subscriptionDowngrade: "Downgrade",
    subscriptionUpgrade: "Upgrade",
    subscriptionUpdated: "Tier berhasil diupdate!",
    subscriptionFailed: "Gagal subscribe",
    subscriptionDowngradeTitle: "Downgrade ke Free?",
    subscriptionUpgradeTitle: "Upgrade ke {name}?",
    subscriptionDowngradeDesc: "Fee akan kembali ke {fee}% dan limit produk {limit}.",
    subscriptionUpgradeDesc: "{value} Credit akan dipotong dari wallet kamu untuk 1 bulan.",
    subscriptionPayUpgrade: "Bayar & Upgrade",
    // kyc
    kycTitle: "Verifikasi KYC",
    kycStatusPending: "Menunggu Review",
    kycStatusApproved: "Disetujui",
    kycStatusRejected: "Ditolak",
    kycNote: "Catatan: {note}",
    kycReviewing: "Admin sedang mereview dokumen kamu.",
    kycApproved: "KYC diverifikasi. Kamu bisa melakukan penarikan.",
    kycRejected: "Hubungi admin untuk submit ulang.",
    kycUploadTitle: "Upload KTP",
    kycUploadDesc: "Diperlukan untuk penarikan pertama. Data aman dan tidak ditampilkan publik.",
    kycFullNameLabel: "Nama Lengkap (sesuai KTP)",
    kycFullNamePlaceholder: "Nama lengkap",
    kycIdNumberLabel: "Nomor KTP (16 digit)",
    kycIdNumberPlaceholder: "3201234567890001",
    kycDigitCount: "{count}/16 digit",
    kycPhotoLabel: "Foto KTP",
    kycPhotoSelect: "Pilih foto KTP",
    kycSubmitting: "Mengirim...",
    kycSubmitButton: "Submit KYC",
    kycFailed: "Gagal submit KYC",
    // tax
    taxTitle: "Laporan Pajak",
    taxLockedDesc: "Fitur ini tersedia untuk tier Pro dan Business.",
    taxUpgradeNow: "Upgrade Sekarang",
    taxSummaryTitle: "Ringkasan Tahun 2026",
    taxGrossRevenue: "Gross Revenue",
    taxPlatformFee: "Platform Fee ({fee}%)",
    taxNetEarnings: "Net Earnings",
    taxEstimationNote: "* Estimasi berdasarkan total earnings. Untuk laporan detail per transaksi, gunakan Export CSV di halaman Analitik.",
    taxDisclaimer: "Catatan: YourPage tidak memotong pajak. Kreator bertanggung jawab atas pelaporan pajak masing-masing sesuai peraturan yang berlaku.",
    // referral
    referralTitle: "Program Referral 🎁",
    referralSubtitle: "Ajak teman daftar dan dapatkan bonus kredit untuk kamu berdua.",
    referralTotalLabel: "Total Referral",
    referralCreditsEarnedLabel: "Total Kredit Diperoleh",
    referralBonusLabel: "Bonus per Referral",
    referralLinkTitle: "Link & Kode Referral Kamu",
    referralLoading: "Memuat...",
    referralCommissionDesc: "Setiap orang yang daftar melalui link/kode kamu akan mendapat {value} kredit bonus, dan kamu juga mendapatkan hal yang sama.",
    referralRegisteredTitle: "Yang Mendaftar via Referral Kamu",
    referralEmpty: "Belum ada yang daftar. Bagikan linkmu!",
    referralLinkCopied: "Link referral disalin!",
    referralCodeCopied: "Kode referral disalin!",
    // feed
    feedTitle: "Feed",
    feedExploreLink: "Explore Kreator →",
    feedLoadError: "Gagal memuat feed.",
    feedRetry: "Coba lagi",
    feedEmptyTitle: "Feed kosong",
    feedEmptyDesc: "Follow kreator lain untuk melihat konten mereka",
    feedExploreCta: "Explore Kreator",
    // overlay
    overlayTitle: "Overlay OBS",
    overlaySubtitle: "Tambahkan URL di bawah sebagai Browser Source di OBS. Alert muncul otomatis begitu ada donasi masuk.",
    overlayBrowserSourceUrl: "URL Browser Source",
    overlayBrowserSourceDesc: "Satu URL untuk tiap widget. Centang 'Refresh browser when scene becomes active' di OBS.",
    overlayDonationAlert: "Alert donasi",
    overlayDonationGoal: "Target donasi",
    overlayCopy: "Salin",
    overlaySending: "Mengirim...",
    overlayTestAlert: "Kirim alert uji",
    overlayTestDesc: "Buka overlay di OBS atau tab lain, lalu klik ini untuk melihat hasilnya tanpa menunggu donasi asli.",
    overlayAppearanceTitle: "Tampilan",
    overlayAppearanceDesc: "Berlaku untuk semua alert donasi.",
    overlayAnimationLabel: "Animasi masuk",
    overlayPositionLabel: "Posisi di layar",
    overlayAccentColor: "Warna aksen",
    overlayTextColor: "Warna teks",
    overlayFont: "Font",
    overlayDurationLabel: "Durasi tampil: {value} detik",
    overlayDurationAria: "Durasi tampil alert",
    overlayAlertTextLabel: "Teks alert",
    overlayAlertTextHint: "Gunakan {donor} untuk nama pendukung dan {amount} untuk jumlah credit.",
    overlayPreview: "Pratinjau",
    overlaySoundTitle: "Suara",
    overlaySoundDesc: "Suara diambil dari tier yang cocok dengan nominal donasi.",
    overlayVolumeLabel: "Volume: {value}%",
    overlayVolumeAria: "Volume suara alert",
    overlayReadMessage: "Bacakan pesan donasi",
    overlayReadMessageDesc: "Pesan pendukung dibacakan otomatis lewat text-to-speech.",
    overlayTtsAria: "Aktifkan text-to-speech",
    overlayTtsMinLabel: "Minimal credit untuk dibacakan",
    overlayTtsMinHint: "Donasi di bawah nilai ini tetap tampil, tapi tidak dibacakan.",
    overlayTierTitle: "Tier alert",
    overlayTierDesc: "Gambar dan suara berbeda sesuai besar donasi. Tier tertinggi yang cocok akan dipakai.",
    overlayNoLabel: "Tanpa label",
    overlayHasSound: "ada suara",
    overlayNoSound: "tanpa suara",
    overlayDeleteTier: "Hapus tier {min} credit",
    overlayEmptyTiers: "Belum ada tier. Tambahkan di bawah.",
    overlayMinCredits: "Minimal credit",
    overlayLabel: "Label",
    overlayLabelPlaceholder: "Super Donatur",
    overlayChangeImage: "Ganti gambar",
    overlaySelectImage: "Pilih gambar / GIF",
    overlaySelectSound: "Pilih suara",
    overlayUploading: "Mengunggah...",
    overlayAddTier: "Tambah tier",
    overlaySaving: "Menyimpan...",
    overlaySaveSettings: "Simpan pengaturan",
    overlayTierAdded: "Tier ditambahkan",
    overlayTierAddFailed: "Gagal menambah tier",
    overlayTierDeleted: "Tier dihapus",
    overlaySettingsSaved: "Pengaturan disimpan",
    overlaySettingsFailed: "Gagal menyimpan",
    overlayTestSent: "Alert uji dikirim ke overlay",
    overlayTestFailed: "Gagal mengirim alert uji",
    overlayUrlCopied: "URL disalin",
    animBounce: "Bounce",
    animBounceHint: "Memantul dari bawah",
    animSlide: "Slide",
    animSlideHint: "Masuk dari samping",
    animFade: "Fade",
    animFadeHint: "Muncul perlahan",
    animSpin: "Spin",
    animSpinHint: "Berputar masuk",
    animDrop: "Drop",
    animDropHint: "Jatuh dari atas",
    animPop: "Pop",
    animPopHint: "Meletup di tempat",
    posTopLeft: "Kiri atas",
    posTop: "Atas",
    posTopRight: "Kanan atas",
    posCenter: "Tengah",
    posBottomLeft: "Kiri bawah",
    posBottom: "Bawah",
    posBottomRight: "Kanan bawah",
  },
  adminFinance: {
    paymentsTitle: "Pembayaran",
    exportCsv: "📥 Export CSV",
    filterPending: "Menunggu",
    filterPaid: "Dibayar",
    filterFailed: "Gagal",
    filterRefunded: "Dikembalikan",
    filterApproved: "Disetujui",
    filterProcessed: "Diproses",
    filterRejected: "Ditolak",
    sortAmount: "Amount",
    sortProvider: "Provider",
    sortUsecase: "Usecase",
    sortDate: "Date",
    sortStatus: "Status",
    sortCredits: "Credits",
    sortDonor: "Donor",
    sortBank: "Bank",
    sortNominal: "Nominal",
    sortEvent: "Event",
    sortTanggal: "Tanggal",
    searchPaymentsPlaceholder: "Cari payer, provider...",
    searchAuditPlaceholder: "Cari event, metode, actor...",
    searchTopupsPlaceholder: "Cari nama donor, user ID...",
    searchWithdrawalsPlaceholder: "Cari bank, nama rekening...",
    paymentCode: "Kode: {code}",
    labelProvider: "Provider:",
    labelUsecase: "Usecase:",
    labelFee: "Fee:",
    labelNet: "Net:",
    labelPayer: "Payer:",
    refundReasonPlaceholder: "Alasan refund",
    refundButton: "Refund",
    editStatus: "Edit Status",
    emptyPayments: "Tidak ada payment.",
    auditTitle: "Audit Trail Pembayaran",
    auditSubtitle: "Catatan permanen setiap pergerakan uang dan credit — siapa, kapan, berapa, dari IP mana.",
    labelAktor: "Aktor:",
    labelCredit: "Credit:",
    labelRef: "Ref:",
    labelWaktu: "Waktu:",
    emptyAudit: "Belum ada catatan audit pembayaran.",
    filterTopupCreated: "Top-up dibuat",
    filterTopupPaid: "Top-up lunas",
    filterTopupApproved: "Top-up disetujui",
    filterTopupRejected: "Top-up ditolak",
    filterCheckoutPost: "Pembelian post",
    filterCheckoutProduct: "Pembelian produk",
    filterDonation: "Donasi",
    filterPaymentRefunded: "Refund",
    filterWithdrawalStatusChanged: "Penarikan",
    eventTopupCreated: "Top-up dibuat",
    eventTopupPaid: "Top-up lunas",
    eventTopupApproved: "Top-up disetujui",
    eventTopupRejected: "Top-up ditolak",
    eventCheckoutPost: "Beli post",
    eventCheckoutProduct: "Beli produk",
    eventCheckoutDonation: "Donasi",
    eventCheckoutChat: "Chat berbayar",
    eventPaymentRefunded: "Refund",
    eventWithdrawalRequested: "Penarikan diajukan",
    eventWithdrawalStatusChanged: "Status penarikan",
    roleUser: "User",
    roleAdmin: "Admin",
    roleFinance: "Finance",
    roleSystem: "Sistem",
    topupTitle: "Top-up Credit",
    breadcrumbAdmin: "Admin",
    breadcrumbTopup: "Top-up",
    selectedCount: "dipilih",
    approveAll: "✅ Setujui Semua",
    rejectAllTitle: "Tolak Semua?",
    rejectAllMessage: "Yakin ingin menolak {count} topup?",
    rejectAllConfirm: "Tolak Semua",
    selectAllPending: "Pilih semua pending ({count})",
    labelDonor: "Donor:",
    labelUser: "User:",
    labelUniqueCode: "Kode Unik:",
    labelTanggal: "Tanggal:",
    notePlaceholder: "Catatan (opsional)",
    approveButton: "Setujui",
    rejectButton: "Tolak",
    rejectTopupTitle: "Tolak Top-up?",
    rejectTopupMessage: "Yakin ingin menolak top-up {amount}?",
    processing: "Memproses...",
    notePrefix: "Note: {note}",
    emptyTopups: "Tidak ada topup.",
    topupApprovedToast: "{count} topup approved",
    topupRejectedToast: "{count} topup rejected",
    withdrawalsTitle: "Penarikan",
    labelNoRek: "No. Rek:",
    labelNama: "Nama:",
    labelCreator: "Creator:",
    markProcessed: "Tandai Diproses",
    rejectWithdrawalTitle: "Tolak Withdrawal?",
    rejectWithdrawalMessage: "Yakin ingin menolak withdrawal {amount}?",
    withdrawalApprovedToast: "{count} withdrawal approved",
    withdrawalRejectedToast: "{count} withdrawal rejected",
    emptyWithdrawals: "Tidak ada withdrawal.",
    profitTitle: "Platform Profit",
    totalRevenue: "Total Revenue (Fee)",
    totalWithdrawn: "Sudah Dicairkan",
    availableToWithdraw: "Tersedia untuk Dicairkan",
    withdrawProfitTitle: "Cairkan Profit",
    nominalPlaceholder: "Nominal (IDR)",
    bankNamePlaceholder: "Nama Bank",
    accountNumberPlaceholder: "Nomor Rekening",
    accountNamePlaceholder: "Nama Pemilik Rekening",
    optionalNotePlaceholder: "Catatan (opsional)",
    withdrawButtonLabel: "Cairkan",
    withdrawalHistoryTitle: "Riwayat Pencairan",
    withdrawRecordedBy: "by {name}",
    withdrawSuccessToast: "Pencairan berhasil dicatat!",
    withdrawFailedToast: "Gagal",
  },
  compAccount: {
    // change-password
    changePasswordTitle: "🔒 Ganti Password",
    changePasswordDesc: "Gunakan password yang kuat dan belum pernah digunakan sebelumnya untuk melindungi akun kamu.",
    oldPasswordLabel: "Password Lama",
    newPasswordLabel: "Password Baru",
    confirmPasswordLabel: "Konfirmasi Password",
    oldPasswordPlaceholder: "Password lama",
    newPasswordPlaceholder: "Min 8 karakter",
    confirmPasswordPlaceholder: "Ulangi password baru",
    passwordMismatch: "Password tidak cocok",
    passwordChangeSuccess: "Password berhasil diubah!",
    passwordChangeFailed: "Gagal mengubah password",
    // auth-guard
    loading: "Memuat...",
    // install-prompt
    installTitle: "Install YourPage",
    installDesc: "Akses lebih cepat langsung dari home screen",
    installButton: "Install",
    installLater: "Nanti",
    // cookie-consent
    cookieMessage: "Kami menggunakan cookies untuk meningkatkan pengalaman kamu.",
    cookieLearnMore: "Pelajari lebih lanjut",
    cookieReject: "Tolak",
    cookieAccept: "Terima",
    // storage-quota
    storageTitle: "Penyimpanan",
    storageUsedOf: "dari {quota} terpakai",
    storageAria: "Penyimpanan terpakai: {pct} persen dari {quota}",
    storageAlmostFull: "Penyimpanan hampir penuh ({pct}%).",
    storageUpgradeDesc: "Upgrade paket untuk menambah kapasitas penyimpanan kamu.",
    storageUpgradeButton: "Upgrade Paket",
    // password-strength
    ruleMinChars: "Minimal 8 karakter",
    ruleUppercase: "Huruf besar",
    ruleNumber: "Angka",
    ruleSymbol: "Simbol",
    // load-more
    loadingDots: "Memuat...",
    loadMore: "Muat Lebih Banyak",
    // infinite-scroll
    noMore: "Tidak ada lagi",
    // confirm-dialog
    confirmYes: "Ya",
    confirmCancel: "Batal",
  },
  compSocial: {
    // post-card
    paidContent: "Konten berbayar",
    topupCredit: "Top-up Credit",
    processing: "Memproses...",
    buy: "Beli {price}",
    writeComment: "Tulis komentar...",
    failed: "Gagal",
    linkCopied: "Link disalin!",
    creator: "Creator",
    user: "User",
    // report-button
    reasonNsfw: "NSFW / Tidak Pantas",
    reasonPlagiarism: "Plagiasi",
    reasonScam: "Penipuan",
    reasonSpam: "Spam",
    reasonOther: "Lainnya",
    report: "Laporkan",
    reportContent: "Laporkan Konten",
    detailOptional: "Detail (opsional)",
    sending: "Mengirim...",
    sendReport: "Kirim Laporan",
    reported: "Dilaporkan",
    // social-auth-buttons
    connecting: "Menghubungkan...",
    continueWithGoogle: "Lanjutkan dengan Google",
    continueWithFacebook: "Lanjutkan dengan Facebook",
    connectFailed: "Gagal menghubungkan ke {provider}",
    // content-protection
    contentProtected: "Konten dilindungi",
    // bottom-nav
    bottomHome: "Beranda",
    bottomChat: "Chat",
    bottomNotifications: "Notifikasi",
    bottomProfile: "Profil",
    mainNavigation: "Main navigation",
    // dynamic-user-title
    routeDashboard: "Dashboard",
    routeManagePosts: "Kelola Post",
    routeManageProducts: "Kelola Produk",
    routeSales: "Penjualan",
    routeDonations: "Donasi",
    routeAnalytics: "Analitik",
    routeWithdrawals: "Penarikan",
    routeCreatorProfile: "Profil Kreator",
    routeSubscription: "Langganan",
    routeSupporterDashboard: "Dashboard Supporter",
    routeWallet: "Wallet",
    routeChat: "Pesan",
    routeNotifications: "Notifikasi",
    routeExplore: "Explore Kreator",
    routeFeed: "Feed",
    routeCreatorPage: "Halaman Kreator",
    titleDefault: "YourPage — Halaman kamu, penghasilanmu",
    titleCreator: "Kreator",
    // offline-indicator
    offline: "Tidak ada koneksi internet",
  },
};
