import type { TranslationDictionary } from "../types";

export const id: TranslationDictionary = {
  common: {
    save: "Simpan",
    cancel: "Batal",
    delete: "Hapus",
    edit: "Edit",
    back: "Kembali",
    close: "Tutup",
    search: "Cari",
    loading: "Memuat...",
    processing: "Memproses...",
    confirm: "Konfirmasi",
    error: "Terjadi kesalahan",
    success: "Berhasil",
    copied: "Link disalin!",
    copyLink: "Salin Link",
    share: "Bagikan",
    notFound: "Tidak ditemukan",
    empty: "Belum ada data",
    filter: "Filter",
    all: "Semua",
    status: "Status",
    actions: "Aksi",
    retry: "Coba Lagi",
  },
  nav: {
    home: "Beranda",
    explore: "Explore",
    dashboard: "Dashboard",
    wallet: "Wallet",
    chat: "Pesan",
    notifications: "Notifikasi",
    profile: "Profil",
    pricing: "Harga",
    howItWorks: "Cara Kerja",
    login: "Masuk",
    register: "Daftar",
    logout: "Keluar",
    adminPanel: "Admin Panel",
    feed: "Feed",
    lightMode: "Mode Terang",
    darkMode: "Mode Gelap",
    selectLanguage: "Pilih Bahasa",
    closeMenu: "Tutup menu",
    openMenu: "Buka menu",
  },
  hero: {
    badge: "⚡ Satu Link untuk Semua Sumber Penghasilanmu",
    titlePart1: "Terima Donasi, Jual Karya &",
    titleAccent: "Bangun Komunitas",
    titlePart2: "di Satu Link",
    subtitle: "Gantikan 3 platform terpisah dengan satu halaman personal. Terima pembayaran instan dari fans via QRIS, e-wallet, dan Bank Transfer tanpa biaya bulanan.",
    ctaPrimary: "Klaim Link yourpage.id Kamu — Gratis",
    ctaSecondary: "Jelajahi Karya Kreator",
    trustFree: "100% Gratis Selamanya",
    trustSetup: "Setup 2 Menit",
    trustPayment: "Support QRIS & Semua Bank",
    statCredit: "1 Credit",
    statCreditLabel: "= Rp 1.000",
    statFee: "5%",
    statFeeLabel: "Fee Terendah",
    statSetup: "2 Menit",
    statSetupLabel: "Halaman Siap Pasang",
    statPayout: "1x24 Jam",
    statPayoutLabel: "Pencairan Saldo",
  },
  earningsCard: {
    title: "Dashboard Kreator",
    monthlyEarnings: "Pendapatan bulan ini",
    growthLabel: "+18% dari bulan lalu",
    newDonation: "Donasi baru",
    productSold: "Produk terjual",
    illustrationNote: "*Ilustrasi tampilan dashboard",
  },
  howItWorks: {
    eyebrow: "Gampang Banget",
    title: "Mulai dalam 3 Langkah",
    step1Title: "Klaim Username Pilihanmu",
    step1Desc: "Daftar gratis dan dapatkan alamat personal yourpage.id/c/namamu dalam 2 menit.",
    step2Title: "Unggah Karya & Tentukan Harga",
    step2Desc: "Pasang harga karya digital, atur target donasi, atau kunci postingan eksklusif.",
    step3Title: "Terima Cuan & Tarik ke Rekening",
    step3Desc: "Fans membayar via QRIS/e-wallet lokal, saldo langsung masuk dompet dan siap ditarik ke bank.",
  },
  howItWorksPage: {
    heroTitle: "Cara Kerja YourPage",
    heroSubtitle: "Panduan lengkap untuk kreator dan supporter",
    forCreatorsHeading: "🎨 Untuk Kreator",
    creatorStep1Title: "Daftar Gratis",
    creatorStep1Desc: "Buat akun dengan email, pilih username. Username akan jadi link halaman kamu: yourpage.id/c/username",
    creatorStep2Title: "Atur Profil",
    creatorStep2Desc: "Upload avatar, banner, tulis bio, tambah link media sosial. Paket Pro/Business bisa kustomisasi warna halaman.",
    creatorStep3Title: "Buat Konten & Produk",
    creatorStep3Desc: "Post gratis atau berbayar (set harga dalam Credit). Upload produk digital seperti e-book, preset, atau template.",
    creatorStep4Title: "Set Donasi & Chat",
    creatorStep4Desc: "Atur target donasi dengan progress bar. Set harga chat per pesan (atau gratis). Setup OBS overlay untuk live streaming.",
    creatorStep5Title: "Terima Pembayaran",
    creatorStep5Desc: "Fans beli konten, kirim donasi, dan bayar chat. Semua penghasilan langsung masuk ke wallet Credit kamu.",
    creatorStep6Title: "Cairkan Dana",
    creatorStep6Desc: "Verifikasi identitas (KYC), lalu tarik saldo Credit ke rekening bank kamu. Min 100 Credit = Rp 100.000.",
    forSupportersHeading: "☕ Untuk Supporter",
    supporterStep1Title: "Daftar & Top-up",
    supporterStep1Desc: "Buat akun supporter. Top-up saldo Credit secara instan via QRIS (1 Credit = Rp 1.000).",
    supporterStep2Title: "Explore Kreator",
    supporterStep2Desc: "Temukan kreator favorit di halaman Explore. Follow mereka untuk update konten terbaru di Feed kamu.",
    supporterStep3Title: "Beli & Dukung",
    supporterStep3Desc: "Buka post atau produk eksklusif, kirim saweran donasi dengan pesan, atau chat privat langsung dengan kreator.",
    supporterStep4Title: "Akses Selamanya",
    supporterStep4Desc: "Konten dan file yang sudah dibeli tersimpan aman dan bisa kamu akses selamanya di menu Library.",
    feeHeading: "💰 Struktur Fee",
    thTier: "Tier",
    thPrice: "Harga",
    thFee: "Fee",
    thCreatorKeeps: "Kreator Dapat",
    freePrice: "Gratis",
    proPrice: "Rp 49.000/bln",
    businessPrice: "Rp 149.000/bln",
    faqHeading: "❓ FAQ",
    faq1Q: "Apakah benar-benar gratis?",
    faq1A: "Ya! Pendaftaran 100% gratis tanpa biaya bulanan tersembunyi. Biaya platform hanya dipotong saat ada transaksi yang berhasil.",
    faq2Q: "Berapa lama pencairan dana?",
    faq2A: "Pencairan dana diproses dalam 1x24 jam kerja langsung ke rekening bank lokal yang kamu daftarkan.",
    faq3Q: "Apakah konten yang dibeli bisa hilang?",
    faq3A: "Tidak. Semua konten dan produk digital yang telah dibeli akan tersimpan selamanya di Library akun supporter kamu.",
    faq4Q: "Bagaimana sistem Credit?",
    faq4A: "1 Credit bernilai tetap Rp 1.000. Top-up via QRIS, gunakan untuk membeli konten atau donasi, dan cairkan ke rekening kapan saja.",
    ctaButton: "Mulai Sekarang — Gratis",
  },
  features: {
    eyebrow: "Semua Ada di Sini",
    title: "Semua Cara Hasilkan Uang di Satu Link",
    subtitle: "Kamu sudah buat konten bagus. Saatnya dihargai.",
    paidPostsTitle: "Post Berbayar",
    paidPostsDesc: "Kunci postingan spesial. Fans bayar 1-klik untuk membaca artikel, komik, atau tutorialmu.",
    digitalProductsTitle: "Produk Digital",
    digitalProductsDesc: "Jual e-book, preset, template, dan materi digital dengan pengiriman file otomatis 24 jam.",
    donationsTitle: "Donasi & Target Goal",
    donationsDesc: "Kumpulkan apresiasi penggemar dengan progress bar target yang transparan dan memotivasi.",
    paidChatTitle: "Chat Berbayar",
    paidChatDesc: "Hargai waktumu dengan menetapkan tarif per pesan untuk sesi konsultasi atau sapaan personal.",
    obsOverlayTitle: "OBS Stream Overlay",
    obsOverlayDesc: "Tampilkan pop-up animasi keren, efek suara lucu, dan GIF saat live streaming.",
    secureContentTitle: "Keamanan Konten",
    secureContentDesc: "Bebas pembajakan dengan proteksi link unduhan aman, watermark otomatis, dan anti-screenshot.",
    analyticsTitle: "Analitik Lengkap",
    analyticsDesc: "Pantau produk paling laris, supporter paling loyal, dan tren pendapatan bulananmu.",
    customPageTitle: "Halaman Personal",
    customPageDesc: "Kustomisasi warna aksen, foto header, dan tautan sosial media agar halaman tampak profesional.",
  },
  feeTransparency: {
    eyebrow: "Transparan 100%",
    title: "Fee Rendah. Sisanya Buat Kamu.",
    subtitle: "Nggak ada biaya tersembunyi. Kamu selalu tahu persis berapa yang kamu bawa pulang dari tiap transaksi.",
    youKeep: "Kamu Bawa Pulang",
    platformFee: "Biaya Platform",
  },
  creditSystem: {
    eyebrow: "Satu Mata Uang",
    title: "Sistem Credit yang Simpel",
    subtitle: "Satu mata uang untuk semua transaksi di YourPage.",
    topupTitle: "Top-up",
    topupDesc1: "Bayar Rp 50.000",
    topupDesc2: "→ Dapat 50 Credit",
    buyContentTitle: "Beli Konten",
    buyContentDesc1: "Post 5 Credit",
    buyContentDesc2: "→ Potong dari wallet",
    donateTitle: "Donasi",
    donateDesc1: "Kirim 10 Credit",
    donateDesc2: "→ Kreator dapat 8–9.5 C",
    withdrawTitle: "Cairkan",
    withdrawDesc1: "Tarik 100 Credit",
    withdrawDesc2: "→ Rp 100.000 ke rekening",
  },
  pricing: {
    eyebrow: "Pilihan Paket",
    title: "Pilih Paket yang Tepat",
    subtitle: "Mulai gratis hari ini, upgrade kapan saja saat kamu berkembang.",
    popularBadge: "Paling Populer",
    freeName: "Free",
    freePrice: "Gratis",
    freeSub: "selamanya",
    freeCta: "Mulai Jualan Gratis",
    proName: "Pro",
    proPrice: "Rp 49.000",
    proSub: "/bulan (49 Credit)",
    proCta: "Pilih Paket Pro",
    businessName: "Business",
    businessPrice: "Rp 149.000",
    businessSub: "/bulan (149 Credit)",
    businessCta: "Pilih Paket Business",
    compareLink: "Lihat perbandingan lengkap semua fitur",
  },
  useCases: {
    eyebrow: "Buat Siapa Saja",
    title: "Cocok untuk Semua Kreator",
    designerTitle: "Desainer & Seniman",
    designerDesc: "Jual preset, template, wallpaper. Upload file, fans download otomatis setelah bayar.",
    educatorTitle: "Edukator & Penulis",
    educatorDesc: "Konten eksklusif, e-book, tips berbayar, dan bangun komunitas loyal.",
    streamerTitle: "Streamer & Gamer",
    streamerDesc: "Terima donasi saat live, overlay OBS kustom, chat santai dengan fans.",
  },
  finalCta: {
    title: "Siap Menghasilkan dari Kontenmu?",
    subtitle: "Gratis selamanya. Upgrade kapan saja. Cairkan kapan saja.",
    button: "Daftar Sekarang — Gratis",
  },
  footer: {
    description: "Platform monetisasi konten untuk kreator Indonesia.",
    productHeading: "Produk",
    pricingLink: "Harga",
    howItWorksLink: "Cara Kerja",
    exploreLink: "Explore Kreator",
    legalHeading: "Legal",
    termsLink: "Syarat & Ketentuan",
    privacyLink: "Kebijakan Privasi",
    contactLink: "Kontak",
    socialHeading: "Ikuti Kami",
    copyright: "© 2026 YourPage. Semua hak dilindungi.",
  },
  auth: {
    loginTitle: "Selamat Datang 👋",
    loginSubtitle: "Masuk ke akun kamu",
    registerTitle: "Buat Akun Baru ✨",
    registerSubtitle: "Daftar gratis dalam 2 menit",
    emailLabel: "Email",
    passwordLabel: "Password",
    confirmPasswordLabel: "Ulangi Password",
    usernameLabel: "Username",
    roleSelectorLabel: "Saya daftar sebagai",
    roleSupporterLabel: "Supporter",
    roleSupporterDesc: "Beli konten, kirim donasi, chat dengan kreator",
    roleCreatorLabel: "Kreator",
    roleCreatorDesc: "Jual konten, terima donasi, buka page sendiri",
    referralLabel: "Kode Referral (opsional)",
    forgotPasswordLink: "Lupa password?",
    loginButton: "Masuk",
    registerButton: "Daftar Sekarang",
    orDivider: "atau",
    loginWithQR: "Masuk via QR Code",
    alreadyHaveAccount: "Sudah punya akun?",
    dontHaveAccount: "Belum punya akun?",
    termsAgreement: "Dengan mendaftar, kamu setuju dengan Syarat & Ketentuan dan Kebijakan Privasi.",
  },
  creatorPage: {
    notFound: "Kreator tidak ditemukan",
    followersCount: "Followers",
    postsCount: "Posts",
    editProfile: "Edit Profil",
    shareProfile: "Bagikan",
    followButton: "Follow",
    unfollowButton: "Unfollow",
    donateButton: "Donasi",
    chatButton: "Chat",
    topSupporterTitle: "Top Supporter",
    becomeMemberTitle: "Jadi Member",
    memberBadge: "✓ Member",
    perMonth: "Credit/bulan",
    supportCreator: "Dukung",
    donateModalTitle: "Beri Apresiasi untuk",
    donateSuccessTitle: "Donasi Terkirim! 🎉",
    donateSuccessDesc: "Terima kasih atas apresiasi dan dukunganmu untuk karya lokal.",
    donateAgain: "Donasi Lagi",
    customAmountPlaceholder: "Nominal lain (min {min})",
    messagePlaceholder: "Pesan (opsional)",
    sendDonationButton: "Kirim",
    paidByCredits: "Dibayar dengan Credit dari wallet kamu",
    tabPosts: "Post",
    tabProducts: "Katalog",
    tabMembership: "Membership",
    emptyPostsTitle: "Belum ada post",
    emptyPostsDesc: "Kreator ini sedang menyiapkan karya terbaiknya. Follow untuk jadi yang pertama tahu saat post dirilis!",
    emptyProductsTitle: "Belum ada produk",
    emptyProductsDesc: "Belum ada produk digital yang dijual saat ini. Ingin request materi? Sapa kreator lewat tombol Chat.",
  },
  post: {
    lockedTitle: "Konten Spesial Terkunci",
    lockedDesc: "Beli sekali, akses selamanya di Library kamu.",
    unlockButton: "Buka Akses Konten Ini",
    previewBadge: "Preview",
    commentsTitle: "Komentar",
    emptyComments: "Belum ada komentar. Jadilah yang pertama!",
    writeComment: "Tulis komentar...",
    sendComment: "Kirim",
  },
  product: {
    filesIncluded: "File yang didapat",
    salesCount: "terjual",
    buyButton: "Beli Sekarang",
    downloadButton: "Download File",
    purchasedBadge: "Sudah Dibeli",
    topupRequired: "Credit tidak cukup. Top-up dulu.",
  },
  wallet: {
    creditBalance: "Saldo Credit",
    topupButton: "Top-up Credit",
    withdrawButton: "Tarik Dana",
    creditRateNote: "1 Credit = Rp 1.000",
    transactionHistory: "Riwayat Transaksi",
    emptyTransactions: "Belum ada transaksi",
  },
  dashboard: {
    greetingMorning: "Selamat pagi",
    greetingAfternoon: "Selamat siang",
    greetingEvening: "Selamat malam",
    totalEarnings: "Total Pendapatan",
    setupTitle: "Setup Halaman",
    newPostButton: "Post Baru",
    myPageButton: "Halaman Saya",
  },
  chat: {
    title: "Chat",
    newChatTitle: "Chat Baru",
    newChatSubtitle: "Kirim pesan pertama",
    pricePerMessage: "Setiap pesan dikenakan {price} Credit",
    inputPlaceholder: "Tulis pesan...",
    sendButton: "Kirim",
    sendFailed: "Gagal kirim pesan",
    conversationsCount: "{count} percakapan",
    emptyConversationsTitle: "Belum ada percakapan",
    emptyConversationsDesc: "Kunjungi halaman kreator dan mulai chat",
    selectConversationTitle: "Pilih percakapan",
    selectConversationDesc: "Pilih chat dari daftar di samping",
    startConversationPrompt: "Mulai percakapan...",
    paidBadge: "Paid",
    sendMessageAria: "Kirim pesan",
    loadFailed: "Chat gagal dimuat",
  },
};
