// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "title": "YourPage API",
    "description": "All-in-One Content Monetization Platform for Indonesian Creators.",
    "version": "1.0.0",
    "contact": {
      "name": "YourPage Support",
      "email": "support@yourpage.id"
    }
  },
  "host": "{{.Host}}",
  "basePath": "{{.BasePath}}",
  "schemes": [
    "http",
    "https"
  ],
  "securityDefinitions": {
    "BearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "Masukkan format: Bearer <token_jwt>"
    }
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "Health check service",
        "description": "Cek konektivitas PostgreSQL dan Redis",
        "tags": ["System"],
        "responses": {
          "200": {
            "description": "System healthy",
            "schema": {
              "type": "object",
              "properties": {
                "status": { "type": "string", "example": "ok" },
                "postgres": { "type": "string", "example": "up" },
                "redis": { "type": "string", "example": "up" }
              }
            }
          },
          "503": {
            "description": "Service degraded"
          }
        }
      }
    },
    "/tiers": {
      "get": {
        "summary": "Daftar platform subscription tiers",
        "tags": ["Platform"],
        "responses": {
          "200": {
            "description": "Daftar tiers (Free, Pro, Business)"
          }
        }
      }
    },
    "/settings/public": {
      "get": {
        "summary": "Pengaturan publik platform",
        "tags": ["Platform"],
        "responses": {
          "200": {
            "description": "Public settings (fee rate, min withdrawal, credit rate)"
          }
        }
      }
    },
    "/platform/qris": {
      "get": {
        "summary": "URL QRIS Platform",
        "tags": ["Platform"],
        "responses": {
          "200": {
            "description": "URL QRIS untuk top-up manual"
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "summary": "Registrasi Akun Baru",
        "tags": ["Auth"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["email", "password", "username", "display_name", "role"],
              "properties": {
                "email": { "type": "string", "example": "kreator@example.com" },
                "password": { "type": "string", "example": "Secret123!" },
                "username": { "type": "string", "example": "kreatorcerdas" },
                "display_name": { "type": "string", "example": "Kreator Cerdas" },
                "role": { "type": "string", "enum": ["creator", "supporter"], "example": "creator" },
                "referral_code": { "type": "string", "example": "BONUS10" }
              }
            }
          }
        ],
        "responses": {
          "201": { "description": "Registrasi berhasil" },
          "400": { "description": "Validasi gagal / email terpakai" }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login Pengguna",
        "tags": ["Auth"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["email", "password"],
              "properties": {
                "email": { "type": "string", "example": "kreator@example.com" },
                "password": { "type": "string", "example": "Secret123!" }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login berhasil (access token, refresh token & Set-Cookie)",
            "schema": {
              "type": "object",
              "properties": {
                "success": { "type": "boolean", "example": true },
                "data": {
                  "type": "object",
                  "properties": {
                    "access_token": { "type": "string" },
                    "refresh_token": { "type": "string" },
                    "user": { "type": "object" }
                  }
                }
              }
            }
          },
          "401": { "description": "Email / password salah atau akun diblokir" }
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "summary": "Refresh Access Token",
        "tags": ["Auth"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": false,
            "schema": {
              "type": "object",
              "properties": {
                "refresh_token": { "type": "string" }
              }
            }
          }
        ],
        "responses": {
          "200": { "description": "Token baru berhasil dibuat" },
          "401": { "description": "Refresh token invalid atau expired" }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "summary": "Logout Akun",
        "tags": ["Auth"],
        "security": [{ "BearerAuth": [] }],
        "responses": {
          "200": { "description": "Logout berhasil & token di-blacklist" }
        }
      }
    },
    "/auth/me": {
      "get": {
        "summary": "Dapatkan Profil Pengguna Login",
        "tags": ["Auth"],
        "security": [{ "BearerAuth": [] }],
        "responses": {
          "200": { "description": "Data user & creator profile" }
        }
      },
      "put": {
        "summary": "Update Profil Pengguna Login",
        "tags": ["Auth"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "display_name": { "type": "string" },
                "bio": { "type": "string" },
                "avatar_url": { "type": "string" },
                "header_image_url": { "type": "string" },
                "page_color": { "type": "string", "example": "#EC4899" },
                "donation_goal_credits": { "type": "integer", "example": 500 },
                "donation_goal_label": { "type": "string", "example": "Beli Mic Baru" }
              }
            }
          }
        ],
        "responses": {
          "200": { "description": "Profil berhasil diupdate" }
        }
      }
    },
    "/creators/search": {
      "get": {
        "summary": "Cari & Filter Kreator",
        "tags": ["Public"],
        "parameters": [
          { "name": "q", "in": "query", "type": "string", "description": "Kata kunci pencarian" },
          { "name": "category", "in": "query", "type": "string", "description": "Kategori kreator" },
          { "name": "limit", "in": "query", "type": "integer", "default": 20 },
          { "name": "cursor", "in": "query", "type": "string" }
        ],
        "responses": {
          "200": { "description": "Daftar kreator terpaginasi" }
        }
      }
    },
    "/creators/featured": {
      "get": {
        "summary": "Daftar Kreator Unggulan",
        "tags": ["Public"],
        "responses": {
          "200": { "description": "Daftar featured creators" }
        }
      }
    },
    "/creators/{slug}": {
      "get": {
        "summary": "Halaman Profil Publik Kreator",
        "tags": ["Public"],
        "parameters": [
          { "name": "slug", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Detail kreator, goal, produk, postingan, dan tier" },
          "404": { "description": "Kreator tidak ditemukan" }
        }
      }
    },
    "/posts": {
      "post": {
        "summary": "Buat Postingan Baru",
        "tags": ["Posts"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["title", "content"],
              "properties": {
                "title": { "type": "string" },
                "content": { "type": "string" },
                "visibility": { "type": "string", "enum": ["public", "paid", "members"] },
                "price_credits": { "type": "integer", "example": 5 },
                "membership_tier_id": { "type": "string" },
                "published_at": { "type": "string", "format": "date-time" }
              }
            }
          }
        ],
        "responses": {
          "201": { "description": "Postingan berhasil dibuat" }
        }
      }
    },
    "/posts/{id}": {
      "get": {
        "summary": "Detail Postingan",
        "tags": ["Posts"],
        "parameters": [
          { "name": "id", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Detail post (konten terkunci jika belum dibeli/berlangganan)" },
          "404": { "description": "Postingan tidak ditemukan" }
        }
      },
      "put": {
        "summary": "Update Postingan",
        "tags": ["Posts"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          { "name": "id", "in": "path", "required": true, "type": "string" },
          { "name": "body", "in": "body", "required": true, "schema": { "type": "object" } }
        ],
        "responses": { "200": { "description": "Postingan berhasil diperbarui" } }
      },
      "delete": {
        "summary": "Hapus Postingan",
        "tags": ["Posts"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          { "name": "id", "in": "path", "required": true, "type": "string" }
        ],
        "responses": { "200": { "description": "Postingan berhasil dihapus" } }
      }
    },
    "/feed": {
      "get": {
        "summary": "Feed Postingan Kreator yang Di-Follow",
        "tags": ["Posts"],
        "security": [{ "BearerAuth": [] }],
        "responses": {
          "200": { "description": "Daftar postingan feed" }
        }
      }
    },
    "/products": {
      "post": {
        "summary": "Buat Produk Digital Baru",
        "tags": ["Products"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["title", "price_credits", "delivery_type"],
              "properties": {
                "title": { "type": "string", "example": "Preset Lightroom Cinematic" },
                "description": { "type": "string" },
                "price_credits": { "type": "integer", "example": 25 },
                "delivery_type": { "type": "string", "enum": ["file", "link", "license_key"] },
                "delivery_content": { "type": "string" }
              }
            }
          }
        ],
        "responses": { "201": { "description": "Produk berhasil dibuat" } }
      }
    },
    "/products/{id}/download": {
      "get": {
        "summary": "Dapatkan URL Unduhan Produk",
        "tags": ["Products"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          { "name": "id", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Presigned download URL" },
          "403": { "description": "Belum membeli produk" }
        }
      }
    },
    "/checkout/post": {
      "post": {
        "summary": "Beli Akses Postingan dengan Credit",
        "tags": ["Checkout"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["post_id"],
              "properties": {
                "post_id": { "type": "string" }
              }
            }
          }
        ],
        "responses": {
          "201": { "description": "Pembelian berhasil & saldo terpotong" },
          "400": { "description": "Saldo tidak mencukupi" }
        }
      }
    },
    "/checkout/product": {
      "post": {
        "summary": "Beli Produk Digital dengan Credit",
        "tags": ["Checkout"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["product_id"],
              "properties": {
                "product_id": { "type": "string" }
              }
            }
          }
        ],
        "responses": { "201": { "description": "Pembelian produk berhasil" } }
      }
    },
    "/checkout/donation": {
      "post": {
        "summary": "Kirim Donasi ke Kreator",
        "tags": ["Checkout"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["creator_id", "amount_credits"],
              "properties": {
                "creator_id": { "type": "string" },
                "amount_credits": { "type": "integer", "example": 10 },
                "donor_name": { "type": "string", "example": "Budi" },
                "message": { "type": "string", "example": "Semangat kontennya!" }
              }
            }
          }
        ],
        "responses": { "201": { "description": "Donasi terkirim" } }
      }
    },
    "/wallet/balance": {
      "get": {
        "summary": "Cek Saldo Wallet",
        "tags": ["Wallet"],
        "security": [{ "BearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Saldo Credit pengguna",
            "schema": {
              "type": "object",
              "properties": {
                "balance_credits": { "type": "integer", "example": 150 },
                "balance_idr": { "type": "integer", "example": 150000 }
              }
            }
          }
        }
      }
    },
    "/wallet/topup": {
      "post": {
        "summary": "Ajukan Request Top-up Credit QRIS",
        "tags": ["Wallet"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["amount_idr", "donor_name"],
              "properties": {
                "amount_idr": { "type": "integer", "example": 50000 },
                "donor_name": { "type": "string", "example": "Budi Santoso" }
              }
            }
          }
        ],
        "responses": { "201": { "description": "Request top-up dibuat" } }
      }
    },
    "/withdrawals": {
      "post": {
        "summary": "Ajukan Penarikan Dana (Kreator)",
        "tags": ["Wallet"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["amount_credits", "bank_name", "account_number", "account_name"],
              "properties": {
                "amount_credits": { "type": "integer", "example": 100 },
                "bank_name": { "type": "string", "example": "BCA" },
                "account_number": { "type": "string", "example": "1234567890" },
                "account_name": { "type": "string", "example": "Kreator Cerdas" }
              }
            }
          }
        ],
        "responses": { "201": { "description": "Permintaan penarikan berhasil diajukan" } }
      },
      "get": {
        "summary": "Riwayat Penarikan Dana Kreator",
        "tags": ["Wallet"],
        "security": [{ "BearerAuth": [] }],
        "responses": { "200": { "description": "Daftar penarikan dana" } }
      }
    },
    "/chat": {
      "get": {
        "summary": "Daftar Percakapan Chat",
        "tags": ["Chat"],
        "security": [{ "BearerAuth": [] }],
        "responses": { "200": { "description": "Daftar percakapan aktif" } }
      },
      "post": {
        "summary": "Kirim Pesan Chat Baru",
        "tags": ["Chat"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["recipient_id", "content"],
              "properties": {
                "recipient_id": { "type": "string" },
                "content": { "type": "string", "example": "Halo, mau tanya soal preset!" }
              }
            }
          }
        ],
        "responses": { "201": { "description": "Pesan terkirim" } }
      }
    },
    "/memberships/subscribe": {
      "post": {
        "summary": "Berlangganan Membership Kreator",
        "tags": ["Memberships"],
        "security": [{ "BearerAuth": [] }],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["creator_id", "tier_id"],
              "properties": {
                "creator_id": { "type": "string" },
                "tier_id": { "type": "string" },
                "auto_renew": { "type": "boolean", "default": true }
              }
            }
          }
        ],
        "responses": { "200": { "description": "Berlangganan berhasil" } }
      }
    },
    "/admin/analytics": {
      "get": {
        "summary": "Admin Platform Analytics",
        "tags": ["Admin"],
        "security": [{ "BearerAuth": [] }],
        "responses": { "200": { "description": "Ringkasan total transaksi, users, volume" } }
      }
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "YourPage API",
	Description:      "All-in-One Content Monetization Platform for Indonesian Creators.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
