upstream backend_stg { server be-stg:8080; keepalive 16; }
upstream frontend_stg { server fe-stg:3000; keepalive 8; }
upstream minio_stg { server minio-stg:9000; keepalive 4; }

server {
    listen 80;
    server_name _;

    client_max_body_size 50m;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location /api/ {
        proxy_pass http://backend_stg;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    location /storage/ {
        proxy_pass http://minio_stg/;
        proxy_http_version 1.1;
    }
    location / {
        proxy_pass http://frontend_stg;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
